### ISSUE TITLE
Tiles in Editor are not Mirrored Properly

### ISSUE THREAD

**Issue by DarkAceZ** [Secretchronicles/TSC#149]
![smc-mirror fail](https://cloud.githubusercontent.com/assets/512326/3870409/1041c0c4-20cd-11e4-96be-f45b78ec5b18.png)

I kind of thought I already reported this, but it's possible it wasn't here on the tracker, so here you are.
When you drag them off of the sidebar, they are mirrored correctly. It's kind of confusing.

**Comment by Quintus** [comment]
> the rotation about X can only be 0 or 180 (flips it up and down), the rotation about Y can only be 0 or 180 (flips it left and right)

The page is correct, I already figured this from the code. I really plead for renaming `m_rot_x` and `m_rot_y` to the more useful names `m_mirror_ver` and `m_mirror_hor` and change their types to `bool`. One gets utterly confused by the naming; what the heck is X and Y rotation in a 2D world? That this means mirroring is something you’d probably not think of. Also, `m_rot_z` should then be renamed to just `m_rot`.

Note that the dimensions (both width and height) of sprites are only ever allowed to be powers of 2, so you don’t need to cater for graphics of other dimensions.

Vale,
Quintus

**Comment by Quintus** [comment]
I have opened #302 for the renaming stuff.

Vale,
Quintus

**Comment by Quintus** [comment]
In https://github.com/Secretchronicles/TSC/issues/323#issuecomment-70551763 @datahead8888 said he dropped this task for now, so I unassign him from it. Feel free to take over.

Valete,
Quintus

**Comment by datahead8888** [comment]
> In #323 (comment) @datahead8888 said he dropped this task for now, so I unassign him from it. Feel free to take over.

I had assumed the convention was to leave it assigned to the person who was looking at it, if they might resume it later, since you are still assigned to the multiple level exits task.  We should probably remove you from that task, too, in case someone else is available to work it in the devel branch.

**Comment by datahead8888** [comment]
> What if when the image is loaded, it is transformed as it needs to be. I've read some online articles about rendering from one GL texture to another, but don't really understand them very well. If that is possible, it seems like something like this could work

All of the tutorials that do this sort of thing that I've found seem to talk about using shaders, which is basically the newer version of OpenGL.  We're still using legacy OpenGL (at least in a number of places -- I haven't really looked through most of the rendering code).
Here's one such tutorial:
http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-14-render-to-texture/

The other option is to look into glReadPixels, which copies a block of data from the frame buffer.  I seem to remember this being the old way of doing things in OpenGL.

We'll basically have to start just trying out different implementations and picking out one that we finally discover works well.  It may drag on for a while.

**Comment by Luiji** [comment]
@datahead8888:
> using shaders, which is basically the newer version of OpenGL

Shaders are a component of the later versions of OpenGL but they are far from basically being it. Newer OpenGL is more about deprecating the function-oriented pipeline in place of vertex arrays.

**Comment by datahead8888** [comment]
I was more worried about conflicts between the types of pipelines if different methods are used, though I have not actually tried this before.  If you know it works, trying a method from one of the tutorials is first priority.

**Comment by brianvanderburg2** [comment]
I've only read a little about the changes in OpenGL.  It doesn't seem to complicated directly, but would require an overhaul of any code (however I know very very little about OpenGL).

Drawing a tile would seem to consist of:
* Binding the texture
* Setting the vertex/texture/normal arrays
* Use glLoadMatrixf to load any custom transforms (instead of glTranslate/glRotate/etc)
    * This may allow using the exact VBOs for each tile, and just use a different matrix to move it to the correct position
    * However, it may be cheaper (in terms of time), to update the VBO each time with the correct coordinates instead of using a matrix (however, a matrix would be required for rotations)
* Draw (glDrawElements)

Documentation I've read indicates that binding a texture can be an expensive operation.  However, I imagine that is more important toward intense 3D graphics (where a single texture may be bound for a model, then draw 10 thousands or more triangles for the model).  Anyway, due to the tiled nature of this game, I don't see any way around binding a different texture each time an object is drawn.  Again, I have no clue what I'm talking about.

**Comment by Quintus** [comment]
TSC still uses the ancient OpenGL 2.x, so at least we should upgrade to 3.x in the nearer future. As for CEGUI, we have been discussing that matter again and again without coming to a definite conclusion.

I don’t know enough about OpenGL to find a solution to this ticket’s problem. Neither do I know enough CEGUI.

I shouldn’t probably have written this answer then.

**Comment by brianvanderburg2** [comment]
If we drop CEGUI, what would we use.  It is a good GUI framework, just very bloated for some uses (I personally hate working with it).  In the past I've coded a very simple python GUI but it only had buttons.  Using the screen system, the basic logic was a screen had a gui pointer, and whenever that pointer was not NULL, any events would be passed directly to the gui object. For draw, the gui would call the normal screen's draw first, then draw itself.  But I'm not a GUI developer so don't know how difficult it would be to create a custom GUI if that were the choice.

**Comment by Quintus** [comment]
I know @Luiji is going to reply to this, but before you do, please switch to the proper ticket: => #10.

Vale,
Quintus

**Comment by datahead8888** [comment]
> I've only read a little about the changes in OpenGL. It doesn't seem to complicated directly, but would require an overhaul of any code (however I know very very little about OpenGL).

@brianvanderburg2, taking a crack at this task is a good way for you to learn more about OpenGL (and CEGUI in general).  I'm not really sure about my available time given school demands.  The reasons I thought it was difficult were the risk of slower implementations, the risk of implementations that don't work at all, TSC architecture complications, and the difficulty in debugging GLSL shader code (you have to use a special tool in order to debug it).  If you start this task, please assign yourself to it so that someone else doesn't redo the exact same work.

Another thing we should probably do is to make a post on a graphics programming site asking what strategy they would recommend (the question would be in reference to approach only).  There are people on sites  more knowledgeable on these questions than any of us.  I've usually found gamedev.net to be a good place for OpenGL questions.

**Comment by datahead8888** [comment]
I would suggest no one work on this issue more until we make a decision on #10.  If we switch to SFGUI as our GUI system, there is a good chance that we will no longer have to deal with issues with Cegui's updating of the mouse cursor or Cegui's sprite rotation systems.  We will just be dealing with SFML and SFGUI at that point.  If we continue using Cegui, however, we will eventually have to explore workarounds with Cegui and/or OpenGL.

Somehow this makes me tempted to switch to SFGUI, but we'll need to look at the larger picture... :P

**Comment by Bertram25** [comment]
Hi guys,

Here are my first impression here:
I must say I was first surprised by Fluxy's fix, but also by the later solutions tested. My first question is, why are you using direct CEGUI texture handling in SMC?
Tell me where I'm wrong, but any GUI API should act as an interface against the rest of the code and that's usually the way to go with CEGUI. I'll try to be more precise in this example:
If I wanted to show a window with tiles in CEGUI, I would create simple frame widgets within the cegui window and set image parameters to them. I would then set a rotation and/or a flip value depending on the desired result, nothing more, no cegui texture involved anywhere by SMC, just setting an image from an imageset.
As for the drag'n'drop (as I suppose there is drag'n'drop support, hence I suppose explaining the first will to link the texture between Cegui and the rest of the code.), You can link cegui event and callbacks and do desired actions based on that.

Also, if you plan to use any other GUI library, you will have in any case to get rid of the link between cegui texture and the rest of the code, right?
Can someone hint me about where and why cegui opengl textures are used within SMC code?

**Comment by Quintus** [comment]
> Can someone hint me about where and why cegui opengl textures are used within SMC code?

The reason is: It is a 10-year old legacy code base written mostly by a single person (FluXy). That person didn’t know better. We have to deal with it.

If you filter our tracker for the "legacy code" tag you will find lots and lots of sins that one should never do in C++ code and which are all well alive in TSC’s code base. Just because the code base is so large we can’t change that all at once.

> Also, if you plan to use any other GUI library, you will have in any case to get rid of the link between cegui texture and the rest of the code, right?

Yes.

Vale,
Quintus

**Comment by Bertram25** [comment]
Ok, so IMHO, the plan could be to upgrade CEGUI to get rid of a few legacy bugs as 0.7 is obsolete anyway, while removing most of CEGUI useless dependency in the code where you see it. I'm pretty sure this effort can naturally lead to some solution of several problems linked to Cegui. :) My two cents, though.

**Comment by datahead8888** [comment]
> Quintus closed this in 7d263b4 18 hours ago

Woo hoo!
