### ISSUE TITLE
Crate Floats in Midair After Falling on an Enemy...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#226]
If you push a crate from a higher position and if it falls onto a pip, it will continue hanging in mid-air.

Quintus mentioned this happens for other enemies, too.

**Comment by datahead8888** [comment]
I'm not sure why a crate would not always kill an enemy, but the collision method really should call the Update_Position_Rect() method to update the collision box for the crate.  A similar bug existed for pips that I fixed.

I took a few minutes to try this alternate version of a fix out, and the crate landed on the ground:
~~~~~~~~~~~~~~~c++
void cCrate::Handle_Collision_Enemy(cObjectCollision* p_collision)
{
    // When a crate falls onto an enemy, it gets killed.
    if (p_collision->m_direction == DIR_BOTTOM && m_vely > 0.5f) {
        cEnemy* p_enemy = static_cast<cEnemy*>(m_sprite_manager->Get_Pointer(p_collision->m_number));
        p_enemy->DownGrade(true);
        Update_Position_Rect();
        //Reset_On_Ground(); // The enemy cannot be ground for us, it was just killed
    }
}
~~~~~~~~~~~~~~~

We might see if we can combine elements of both this fix and Quintus's fix and see how it works with more testing when someone has time.

**Comment by Quintus** [comment]
I think the problem is the collision handler isn’t actually run on `cCrate`, but on the respective enemy. Remember that the collision handler will always run on the object that is moving, and if both objects are moving, it’s hard to predict which object’s collision handler will run. There’s a method that passes execution to the other object’s collision handler, but I don’t remember its name right now. The collision system may need an entire rework to prevent that. Just grab a star, place Alex in front of a furball, stand still, and let the furball walk by. It will not be killed, although you have a star. Guess the reason? The collision handler is run on the furball, not on Alex, and only Alex’ collision handler has the star death clause.

Vale,
Quintus

**Comment by datahead8888** [comment]
Should the Update_Position_Rect usually be called for a collision event method for an enemy/object?

I had found that for the Pip issues, the small pips sometimes hung in the air for a little bit above the ground before finally falling to it.  This issue became more common after doing the other parts of the pip fix.  While debugging, I found that collision box information was incorrect, and calling this method corrected this issue.  Whether or not it fully fixes the crate issue is of course another question.

If it is not clear for whom a collision handler will run and if it is causing issues, we should probably open a new bug ticket on it.  I can't really look into these issues much right now myself, unfortunately.

**Comment by Quintus** [comment]
`Reset_On_Ground()` is the method that is responsible for checking whether there is something below the sprite to hold it. If it isn’t, `m_is_on_ground` will be set to `false` and then the gravity update function will take effect on the sprite until it hits something massive or halfmassive below. Enemies count as massive.

>  While debugging, I found that collision box information was incorrect, and calling this method corrected this issue.

You might be correct with that. Maybe it’s a combination of `Update_Collision_Rect()` and `Reset_On_Ground()`.

Vale,
Quintus
