### ISSUE TITLE
Replace level finish song

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#238]
We probably need another level finish song.

Valete,
Quintus

**Comment by datahead8888** [comment]
For now I'm uploading a screenshot of the licensing for these songs to this ticket.

![jan-01-2015-open-surge-level-ending-music-license](https://cloud.githubusercontent.com/assets/6478551/5593765/45aa9fea-91f4-11e4-8404-363caa1526e0.png)

**Comment by datahead8888** [comment]
I've added all the versions of the level ending music to the release branch and changed the game code to use courseclear_A.ogg.  This has been pushed to the release-2.0.0 branch.

A couple future thoughts:
* We might make the music begin immediately playing when the player takes an exit rather than wait until the graphic effect is finished
* Some of the songs have a slight pause at the end.  This may be fine for level ending music, but we may think about whether we want to trim them a little (or at least configure them differently once we change TSC so that it can auto-loop songs and start and begin a song at any point).
