### ISSUE TITLE
Replace Super-Mario-World-style dying music...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#260]
When you die in a level, a remix of the Super Mario World dying music is played.  We will probably have to request a new song from a musician, unless we're lucky enough that someone has already written a tune like this.

Also, where is the music file for this?  I have never been able to find it...

**Comment by Luiji** [comment]
Whether or not it should be classified as sound or music, for technical reasons should resolve to the question of whether it's short enough to practically be kept in memory at all times, as with all other sound effects.

It could be practical to classify the death music as music due to the fact that it plays in place of other music and lasts a fair length of time, and shouldn't happen at as high of a rate as other sound effects.

**Comment by datahead8888** [comment]
Silen has volunteered for this task.
See: http://gamejolt.com/community/forums/topics/secret-chronicles-urgent-need-for-music/5645/#post-36339

**Comment by datahead8888** [comment]
Silensir has made a licensing statement for the dying music.  He did make the mistake of mistyping the URL (because he saw a slightly abbreviated form by sound cloud using .. to remove part of the URL when viewed).  I would assume this is sufficient, but let me know if there are any concerns.  Here is a screenshot of the confirmation:

![screenshot from 2015-03-03 17 29 07](https://cloud.githubusercontent.com/assets/6478551/6473980/3e03628e-c1cb-11e4-9418-14789c3747e5.png)

**Comment by Quintus** [comment]
This is sufficient.

Vale,
Quintus

**Comment by Quintus** [comment]
See 66c3ba91a329d98c34408fee6d2eaef40a0b7b31.

Vale,
Quintus
