### ISSUE TITLE
Odd glob in corner of game

### ISSUE THREAD

**Issue by sydneyjd** [Secretchronicles/TSC#309]
Hey all you TSC peoples. :D @datahead8888 told me to leave a issue report here, so thats what im doing.

Here is a screenshot. I have only seen it in the 4th level. It does not get in the way of, or hinder Alex's performance.
![3](https://cloud.githubusercontent.com/assets/8949851/5601658/081e51a0-92dd-11e4-9a76-263dd46f4421.png)

**Comment by datahead8888** [comment]
That's the moon background graphic.  I think we might consider changing how it moves though, since it kind of hops with Alex.

At http://forum.secretchronicles.de/topics/168:
> In the third level in the normal game, I like the moon background that was added. However, it almost seems to "jump" up when Alex jumps. Might it be appropriate to change its movement so that it moves a bit slower relative to the other backgrounds in front of it?  I tried changing the speed X and Y attributes for it, and they seem to have no effect...

**Comment by datahead8888** [comment]
Also, @sydneyjd  -- do you think we should change its size or color?  I'm going off what you said in IRC.  We could also look at having multiple moon images if desired.

**Comment by Quintus** [comment]
Errm, what’s the issue in this ticket? The moon looks just fine to me, doesn’t it?

>  I think we might consider changing how it moves though, since it kind of hops with Alex.

It doesn’t move. The camera moves. You can have this with any other background graphic, but with the moon it just is more noticable.

Vale,
Quintus

**Comment by datahead8888** [comment]
> Errm, what’s the issue in this ticket? The moon looks just fine to me, doesn’t it?

@sydneyjd was originally mistaken about what it was, and I didn't know what he was referring to until he opened the ticket.  My thought on what we might change is the vertical scroll speed so that it scrolls vertically slower.  The moon is in space and is much farther than about any other background item.  Thus I would have expected it to scroll slower.  I could not seem to get it to change when I tried changing the level settings, though.

I think Sydney thought we might consider a different appearance for it, too.  That of course is not a bug but is worth discussing.
