### ISSUE TITLE
Unclear licensing for assets

### ISSUE THREAD

**Issue by kozross** [Secretchronicles/TSC#325]
Some assets are described as having a license of 'special', without indicating what the hell that means. Others have author attributions with no licenses, which legally defaults to 'all rights reserved'.

Could I please receive some clarification on this, or even better, a list of *every* license used for assets in this game?

**Comment by datahead8888** [comment]
Hello, and welcome to The Secret Chronicles of Dr. M (Also known as The Secret Chronicles or TSC).  This project is a fork of SMC (Secret Maryo Chronicles), which was run for about 10 years before we started.  Thus any licensing issues it had we will have inherited.

> Some assets are described as having a license of 'special'
Yes, we have been using special for some assets.  @Quintus would probably be in a better position to explain this, since he has a strong background in law.

> Others have author attributions with no licenses, which legally defaults to 'all rights reserved'.
Could you give some examples of ones you have found like this?  Any help fixing licensing is appreciated.

I found some files that apparently never specified licensing to start with while working on small pipes replacements.  I've corrected those files after replacing them with new graphics, but I wouldn't be surprised if there are more files like this.  We probably need to design and run a script to search all image settings files that correspond to png's and report which ones don't have author/license information.  We could try to do something similar for music.

@Quintus has been leading the effort to clean up our licensing system and eliminate other legal issues.  The reason why we've been delaying release 2.0 for TSC has been so that we can purge obvious Mario references to eliminate legal issues.  If we have incorrect licensing attributions in files, though, that is probably also a legal issue, in which case this task should be marked as a blocker for the release.

> a list of every license used for assets in this game
This would take more time to produce, but we can see what works.

Also, drop by our IRC chat room in #secretchronicles or our website at http://www.secretchronicles.de.  We're always glad to see new faces.

**Comment by Quintus** [comment]
The licensing in the original SMC was a mess. We are in the process of cleaning the rests up.

> Some assets are described as having a license of 'special', without indicating what the hell that means. 

Read the README. There’s a paragraph at the end of the file that explains the licensing and its problems.

> Could I please receive some clarification on this, or even better, a list of every license used for assets in this game?

Make magic happen. The artists who created these are gone and the assets which were created by them were contributed under the “Original SMC Contribution license”, which is also mentioned in the README and which is included in the repository for your convenience. This won’t really make it better, though, because that license is misleadingly worded and allows for way to much interpretation.

> Others have author attributions with no licenses, which legally defaults to 'all rights reserved'.

You really didn’t read the README, did you?

Vale,
Quintus

**Comment by datahead8888** [comment]
@Quintus, do you think we can close this, or do you want to use this ticket to track any other licensing clean ups in general?

**Comment by Quintus** [comment]
> do you want to use this ticket to track any other licensing clean ups in general?

No.

> do you think we can close this

@kozross Has the licensing become more clear to you? We’re working hard to get everything new under CC-BY 4.0, but all the existing SMC assets are probably GPLv3ish, although not completely -- see the [original SMC contribution license](https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/docs/pages/old_smc_contribution_license.md), which is not really understandable. The one thing that is “special” is the title theme music because that’s some very unique and distinguishing piece we would like to restrict to this game. We are discussing this internally, though.

All the code is of course GPLv3+.

Vale,
Quintus

**Comment by kozross** [comment]
@Quintus Yeah, it's clear to me now, thanks.

**Comment by datahead8888** [comment]
Closing...
