### ISSUE TITLE
File format extensions

### ISSUE THREAD

**Issue by Luiji** [Secretchronicles/TSC#342]
Currently the file format extensions are `.smclvl`, `.smcsav`, etc. Should we change these to `.tsclvl`, etc.?

**Comment by datahead8888** [comment]
I agree.  I think they should be changed.

We might think about how many thinks need to be changed before putting in inside the release-2.0.0 branch, though.  If possible, it'd be really good to get this into the release so that it matches our new name of the game.

**Comment by Quintus** [comment]
I agree with @datahead8888. If we don’t change the file extension in our first release, we will have a hard time to change it later on. So yes, this should go into 2.0.0. If you do this, please do the code change and the renaming of the level files in the repository in two separate commits, because it will otherwise make the diff very large, hiding the actual code change. I’ve done this mistake before, and it’s better to not repeat it.

Vale,
Quintus

**Comment by Luiji** [comment]
Above commits are tested and working, but there's one more thing we need to cover before I cherry-pick this into release and mark this as closed.

https://github.com/Secretchronicles/TSC/blob/devel/tsc/src/core/filesystem/resource_manager.cpp#L360

`cResource_Manager::compat_move_directories` will need to be updated to rename file extensions accordingly. I have a pair of questions before making modifications, though.

(1) According to line 93, this code is only executed for UN*X systems (including GNU/Linux). Do we ever intend to create compatibility moves for Windows?
(2) Do we actually want to do this at all? Since TSC is a fork of SMC, should we consider them separate projects that can operate independently and, at the same time, be installed on the same computer simultaneously? Perhaps we should additionally consider this if we intend to remove compatibility code for old versions of the level formats, since older SMC levels (including those made by users) may not be compatible anymore.

**Comment by Quintus** [comment]
> (1) According to line 93, this code is only executed for UN*X systems
> (including GNU/Linux). Do we ever intend to create compatibility moves
> for Windows?

The compat_move_directories() function was added way before we
officially forked. It was created because we switched from ~/.smc to
~/.config/smc and other XDG directories, and it was never intended to be
used for a SMC->TSC move. That’s also why it isn’t run on Windows:
Windows doesn’t have XDG, and the Windows data directories were not
changed when the function is introduced.

> (2) Do we actually want to do this at all? Since TSC is a fork of SMC,
> should we consider them separate projects that can operate
> independently and, at the same time, be installed on the same computer
> simultaneously?

I agree with this. I think the function can be removed without further
replacements. SMC and TSC are two separate projects now, and if SMC ever
gains momentum again, its new developers would probably be quite angry
if we “stole” users their data this way.

Vale,
Quintus

**Comment by datahead8888** [comment]
TSC 2.0 will still be able to read .smclvl files, correct (assuming the user placed one in his/her TSC data directory)?  I think we would want these to be reverse compatible within the 2.X line of releases.

> Do we actually want to do this at all? Since TSC is a fork of SMC, should we consider them separate projects that can operate independently and, at the same time, be installed on the same computer simultaneously? Perhaps we should additionally consider this if we intend to remove compatibility code for old versions of the level formats, since older SMC levels (including those made by users) may not be compatible anymore.

You  mean that we would not try to convert the old SMC user data directories into TSC user data directories, correct?  That makes sense.

I remember @Quintus saying a while back that the install program tries to auto convert some SMC data into TSC data.  Is this true at all (or is this what you were talking about above)?  We'd want consistent behavior in the TSC installer.
