### ISSUE TITLE
Default Packages for Installation...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#347]
This is a task to create a couple default packages to be included with the TSC installation so that new users will be exposed to the concept of packages and get an idea what they do, along with an example.

In #106, @brianvanderburg2  suggested:

> For demo purposes so users can try them out, perhaps two packages can be provided. One package would contain only media such as graphics, while another package could also contain levels. This would demonstrate the two purposes of packages (1 - The ability for a developer to isolate his/her own levels, worlds, campaigns, saves, etc. 2 - The ability to create resource-only packages that can be used by other packages.

cc @brianvanderburg2

**Comment by brianvanderburg2** [comment]
One idea is to make the main game files (the levels/worlds/campaigns) a package.  Then we could have multiple parts to the game, each represented by a package.  Since the game is called "The Secret Chronicles of Dr. M", the first package could be "TSC/Chronicle 1", then later we could create another "TSC/Chronicle 2" and so on.

**Comment by Quintus** [comment]
With the package system being on hold indefinitely, there is no point in keeping this open.
