### ISSUE TITLE
New hedge replacement is out of sorted order...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#361]
In the level editor, under section "Hedges", we have "2 Small 1", "2 Small 3", "2 Small 4", and "2 Small 2" (our newest hedge graphic replacement) is a couple items down from this last one.  It really should be between the others numerically.

I had missed this originally and then couldn't figure out why it was happening.  Thus I'm creating a ticket to let everyone discuss it.

Well...looking back...big hedges are out of order a bit, too.  We will either close this as not-a-bug or move it back to bug again.

![hedge ordering mystery](https://cloud.githubusercontent.com/assets/6478551/6091080/9bfd3f8a-ae67-11e4-9893-72b790f8676f.png)

cc @sydneyjd

**Comment by Quintus** [comment]
AFAIK, the order for static graphics in the list is just the order of the files on the file system. If you ever iterated a directory in a programming language other than Shellscript, you know what that means: Basically undefined, because each file system does it different. I agree that we should probably order them alphabetically, but the issue is more general than just this hill.

For nonstatic sprites this does not happen because their order is defined in `data/editor/level_items.xml`.

Vale,
Quintus

**Comment by datahead8888** [comment]
I agree.  This is not a bug, but we might consider implementing a feature to handle this better.

**Comment by datahead8888** [comment]
The needed feature is addressed in #371
