### ISSUE TITLE
Implement Sort Order for Static Sprites in Level Editor...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#371]
In the level editor static sprites such as the hedges do not have a sort order defined and may display in any order.  It is believed this corresponds to the order in the file system.

Quintus found that non static sprites have their order defined in data/editor/level_items.xml

This is a task to:
1. Allow the order for any static sprite to be defined in an XML file
2. If an item is not found in the XML file, default to an alphabetic ordering

If anyone thinks this should be marked "Bug" instead of "Feature", feel free to speak up.

**Comment by Bugsbane** [comment]
I've yet to come across any situation where sort order got in my way, so I'd keep it as a feature.

**Comment by Quintus** [comment]
The relevant point to add this is in [`cEditor::load_image_items()`](https://github.com/Secretchronicles/TSC/blob/db0effe6c432715cbaffb57e5c16a4304d05df10/tsc/src/core/editor/editor.cpp#L966), which reads the list of static sprites from the data directory. However, the actual item settings file is parsed in [`cEditor::Try_Add_Image_item()`](https://github.com/Secretchronicles/TSC/blob/db0effe6c432715cbaffb57e5c16a4304d05df10/tsc/src/core/editor/editor.cpp#L779) when the collected list of filenames is already being iterated. Since the sorting needs to happen not based on the filename, but based on the information in the settings file, this requires some restructuring of those two methods.

**Comment by Quintus** [comment]
What needs to be considered here is that while static sprites have their name specified in their respective `.settings` file, everything else receives its name from C++ code. These letter items also are usually marked as translatable strings. Thus, alphabetic order is not at all that obvious -- alphabetic on the filename, on the untranslated string, on the translated string? How should the untranslatable static sprites behave with regard to the translatable ones?

Maybe it's better to remove the display of the static sprites' names from the editor's menu alltogether. After all, these names are mostly internal and not useful anyway. I mean, things like `blue_1` do not convey any useful information anyway, does it?

**Comment by Quintus** [comment]
I've now just chosen to sort by the settings file's `name` property. I'm satisified with the results.
