### ISSUE TITLE
Secret Area Markers

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#385]
I’ve been playing Supertux today, and I really liked how they show you the number of available secret areas in a level and print a message when a secret area is entered. I think we should have that too. This requires special markers for secret areas that can probably be implemented like the enemy stoppers.

Vale,
Quintus

**Comment by datahead8888** [comment]
Would these special markers for secret areas just be a different level exit object?  You don't mean a special square in addition to the normal exit, correct?  Otherwise people might forget to put the extra square by the exit.

We also might add a check that a user actually has a normal exit in a level.  It could print a warning if one does not exist (and take some default behavior if a level with no normal exit is played).

**Comment by Quintus** [comment]
I wasn’t suggesting to add any exits. Secret areas are not always exits
after all, and currently, they even can’t. They _might_ contain special
exits once we have implemented them, but this suggestion is much more
general. Basically, I just want to print a message to the screen when a
secret area is found and have an overview of the number of secret areas
for the user available so he can pursue them.

You see, nothing to do with exits :-)

**Comment by datahead8888** [comment]
Yes, this makes sense for secret areas.  We might look into allowing the user to drag and drop the rectangles to arbitrarily control the sizes.  Otherwise, if the rectangles are always small, level creators will have to force the player to pass through a narrow location or pipe in order to guarantee it is triggered.

How will secret exits be differentiated from normal exits?

**Comment by Quintus** [comment]
> How will secret exits be differentiated from normal exits?

This probably belongs in its own ticket.

Vale,
Quintus

**Comment by datahead8888** [comment]
> This probably belongs in its own ticket.

I would say just to put it in #19 because this is a fundamental part of adding multiple exits to the game.
