### ISSUE TITLE
Accessing wn_05_top crashes game.

### ISSUE THREAD

**Issue by Danfun64** [Secretchronicles/TSC#389]
For some reason, whenever the game loads the level wn_05_top, it crashes. Is there a reason why?

**Comment by datahead8888** [comment]
I was able to access this level fine without a crash.  I was using a slightly modified version of TSC, though all I changed were images and compatibility code.  Does anyone else have this problem when playing wn_05_top?

@Danfun64 - could you follow these instructions and see if you can get any error messages when crashing the game?
http://wiki.secretchronicles.de/Creating%20a%20GDB%20stacktrace

With an appropriate error message, we can better interpret what the problem may be for you.

**Comment by Danfun64** [comment]
http://paste.debian.net/?hidden=689346d7;lines=0

**Comment by datahead8888** [comment]
Were there any other error messages or warnings in your console output?

Which branch were you using (release-2.0.0 or devel)?

**Comment by Danfun64** [comment]
devel. As for your other question, can you wait a minute?

**Comment by Danfun64** [comment]
http://paste.debian.net/hidden/1db5828c/

**Comment by georgerbr** [comment]
I was able to reproduce the crash, and made a naïve patch against `e6e012a3a0776df825cd0e5377eebc10a1c389ea` to fix it.

http://pastebin.com/rzeq5aJR

**Comment by Quintus** [comment]
@georgerbr Thanks, I have applied your patch. It would be nice if you used `git commit` and `git format-patch` the next time you contributed, because this a) ensures author and time information is set properly and b) the patch is formatted correctly. I got this when I applied it:

~~~~~~~~~
% patch src/level/level_loader.cpp platformfix.patch 
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/level/level_loader.cpp
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 727 with fuzz 1
~~~~~~~~~

Using `git format-patch` should prevent that. Thanks for your work anyway :-)

Vale,
Quintus
