### ISSUE TITLE
Locate Old SMC Subversion Repository...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#397]
It's about time we put some firepower behind this task.  We need to get a copy of the old subversion repository with all of its SMC history and put it on the Alexandria server for internal reference.

@brianvanderburg2 - do you have a copy of this repository?

@SonOfBowser - do you have a copy?

@BodhiPeace - do you have a copy?

If no one has a copy, our remaining options are:
* Ask the administrative staff on sourceforge.com if they can fix the broken link to view the history or if they can give us a copy.  It is probably best if someone previously set up for sourceforge for SMC did this.
* Ask FluXy if he can give us a copy.

I labeled this as "WebSite" because we need to put a copy on the Alexandria server.  It would probably only be made accessible to contributors.  However, I'm putting it in this github project because it involves getting the old source code history on which we are dependent and because most team members do not watch our website project in github.

**Comment by SonOfBowser** [comment]
I have an old checkout, but as far as I can tell, that's pretty much useless in SVN because history is always queried against the server, and that's now not responding.

Don't think this is anything to do with sourceforge, because the SVN was always hosted externally on opensvn.csie.org, which is now just showing a shutdown page from 2010. Not sure if anyone's still contactable there, or if anyone got a dump of old SVN history (that was about the time we moved to Github, so maybe no one bothered?)

**Comment by Quintus** [comment]
> Security issue? SECURITY ISSUE! Well, that sounds bad.

Errm, this is new to me. I have not actually checked if the TSC sourcecode due to its SMC heritage contains malware from that period around 2010. Though from what I have seen (and I think I’ve touched nearly every file at least for reading), I’ve not seen any malicious code in our codebase.

> We need to get a copy of the old subversion repository with all of its SMC history

Do we really need that? I originally wanted one for legal reasons so we can find out who really has contributed all over time and fill gaps in our investigations, but for the reasons SonOfBowser gave above I think this is in vain. the SVN history is on the SVN server, and the SVN server is gone. This renders both us and any third party unable to see who contributed before the Git move. Which in turn means that any one who claims to hold rights on TSC’s code is unable to proof that. He cannot have the history.

Valete,
Quintus

**Comment by datahead8888** [comment]
> Do we really need that?

We've already seen instances in the ticket for the CEGUI rotation issue where old history was helpful.  If it is possible to obtain, it is worth obtaining, in my opinion.  If every person we ask does not have it and if it finally turns out the people at the hosting site do not have it anymore, obviously this will not be possible.

**Comment by datahead8888** [comment]
SonOfBowser said:
> and also suggests that even FluXy has/ had no way to recover the SVN history

Actually, it looks like FluXy did have some SVN history that he attempted to import into github.  It was taking forever, and he thought it might be due to disk space issues in github:

FluXy said:
> I started the github "SVN Import" around 5 days ago but it still shows "This repository is currently being imported. It should be ready soon."
Should we start the new git repository without the SVN history ?
(Probably also better for the Disk Space space limit on github.)

> Canceled the import now.

**Comment by SonOfBowser** [comment]
>> Security issue? SECURITY ISSUE! Well, that sounds bad.

> Errm, this is new to me. I have not actually checked if the TSC sourcecode due to its SMC heritage contains malware from that period around 2010. Though from what I have seen (and I think I’ve touched nearly every file at least for reading), I’ve not seen any malicious code in our codebase.

That was about a security issue in the CSIE site; nothing to do with any individual project on it.


> Actually, it looks like FluXy did have some SVN history that he attempted to import into github. It was taking forever, and he thought it might be due to disk space issues in github:

I'm fairly sure this feature would just pull the history from the SVN server and convert it to Git history (probably using [git-svn](https://www.kernel.org/pub/software/scm/git/docs/git-svn.html) ). It was taking forever because the SVN server was broken.

**Comment by datahead8888** [comment]
> It was taking forever because the SVN server was broken.

Thank you for explaining.  I'd still like to see if Brian Vanderburg, Bodhi, or FluXy has a copy.

I probably will check with Quintus before sending any emails to FluXy, though, since he can be hard to reach.

**Comment by brianvanderburg2** [comment]
At one time I had a checkout on my computer, but it seems like I've deleted it when I switched over to the github repository.

**Comment by SonOfBowser** [comment]
> Thank you for explaining. I'd still like to see if Brian Vanderburg, Bodhi, or FluXy has a copy.

Best case would be if someone was already using git-svn before the SVN server broke, and still has the repo. Seems very unlikely, but you never know. Of course, if we'd had this before starting the original github repo, we'd have all later history on top of this, so we wouldn't have this problem.

**Comment by datahead8888** [comment]
I just like to check all possible avenues before giving up on something.  If you are correct, SonOfBowser, this ticket will eventually be closed with no further action possible.

**Comment by Quintus** [comment]
> That was about a security issue in the CSIE site; nothing to do with any individual project on it.

What I was referring to: Someone broke into the CSIE site and tempered with the code of the individual projects to inject malware into them. Just to have my thoughts clear.

Vale,
Quintus

**Comment by datahead8888** [comment]
Superceded by: https://github.com/Secretchronicles/main-website/issues/11
