### ISSUE TITLE
Remove or Replace Pipes and Mushrooms in Worldmap

### ISSUE THREAD

**Issue by sydneyjd** [Secretchronicles/TSC#406]
I just realized that we still have mushrooms and the old style pipes on the worldmaps. I don't consider it a blocker, but it is a issue we should discuss. Can we get them removed and possibly the ugly corn with them?

Any opinions or thoughts?

http://www.zimagez.com/full/8cf3cfc85edc20f4817defaa1cf6b7540244c106ec467e636924c0fb25bf0a9d9e4cf7af55047ce82a755e505ca1ccdeb322beb4ea6b5c5e.php

**Comment by Quintus** [comment]
@sydneyjd The link is broken. You can upload screenshots directly here in GitHub, which is recommended for things like this. Click the “selecting them” link below the comment editbox to do so.

Vale,
Quintus

**Comment by sydneyjd** [comment]
Oops, sorry about that.
![8cf3cfc85edc20f4817defaa1cf6b754893a3beeae69a43b6924c0fb25bf0a9d9e4cf7af55047ce82a755e505ca1ccdeb322beb4ea6b5c5e php](https://cloud.githubusercontent.com/assets/8949851/6931472/9dd96a20-d7db-11e4-9846-a552716b579b.png)

**Comment by datahead8888** [comment]
The style of the pipes looks like Nintendo's, as opposed to the more slanted tops we have on our pipes in the levels.  The screws would never have to be drawn on the map, because at such a small size they wouldn't be visible at that scale anyways.  I could see an argument for this being "Blocker", but I'm open to discussion.

The mushroom is a completely different style than what we've seen in Nintendo mushroom or our old power up mushrooms that looked like them.  We probably should change it, but I'm not thinking it's a Blocker.

Here are some options:
* Remove all pipes and the mushroom outright, removing the image files and the usage in the world maps.  Would this look bad?
* Remove the pipe and mushroom graphic files.  Replace them with other objects in the world editor for each world.
* Hurriedly do a pipe replacement.  @sydneyjd - do you know if this is feasible?  We could use a "quick and dirty" one for now, since the world map currently doesn't have many detailed graphics at all.  We could change it again later.
* We could also hurriedly do a mushroom replacement if there is time.
* The remaining option is of course to change nothing, which may run some risk of Mario clone-isms.

**Comment by datahead8888** [comment]
> Though pipes on a world map don’t make sense if you don’t want to be a Mario clone, so we should better remove them mid-term and entrich world map scenery with more bushes, trees, ruins, whatever.

Yes, given the amount of effort we've put into not being a Mario clone in release 2.0, I really lean towards our needing to address this in the release.  It would be a shame to have people immediately see the world map and think, "Mario Clone".

Are there any level objects besides small pipes that could be scaled down and put on the world map?  This might widen our options.  Otherwise we could temporarily borrow something from a website and maybe remove it in a later release.

Truth be told, though, we may not stop being viewed as a Mario clone until we make some more fundamental changes in later releases.  This world map problem, however, probably is something that can be changed now.

**Comment by datahead8888** [comment]
Per our discussions in IRC, I have marked this task Blocker.  If anyone else on the team disagrees, feel free to speak up.  My feeling is that if we were willing to remove the turtle boss and title music due to license violations, Mario-like mushrooms/pipes on the map should be given the same treatment.

**Comment by datahead8888** [comment]
@sydneyjd - in answer to your question, to do a git pull for the release, do the following:
git checkout release-2.0.0
git pull origin release-2.0.0

--Here, I used pull, which actually merges it into the current branch.  There are other variations people use on the command, but this is how I usually do it for the release branch itself.

**Comment by datahead8888** [comment]
@sydneyjd - how hard do you think it would be to create some sort of replacement for the pipes (whether it be a resized graphic as Quintus suggested) or something else?  The main thing is that they don't look like Nintendo pipes.

Would you recommend doing that replacement or removing the pipes?

Does anyone have a problem with just removing the mushrooms?  This is less likely to cause controversy than the hedges did, since most people don't make maps.

I still think we ought to address this in the release (since this is a clear cut Mario reference and is also seen in the first map in the game), but we need to come to decisions soon to avoid any risk of this issue impacting us.

**Comment by sydneyjd** [comment]
If we do i would just shrink down the mini-pipes, but pipes are not the 
"big thing" in the game, so i would prefer to just remove them. It would 
seem that a mario clone would have them. We should have something else 
on the worldmap instead of pipes, maybe furballs.
My thoughts. ;)

-Sydney

**Comment by datahead8888** [comment]
Furballs on the map are an interesting idea, though we don't want to overuse them, either.  We might also put some other enemies on the map - ie armies - this would solve the problem as to what we should do about the mushrooms.

I wonder if there is any filter we could use to do a little different map style for them.  That said, I don't think we should try to make them "look like" the style for other objects on the map - we might try to find a more detailed map style for all objects going forward.

**Comment by Quintus** [comment]
I tried my hand on minifying the existing pipes (both the normal and the small ones) for the map, but it turns out that either will look bad on the map, because the size is so small that the outlines blur. It is required to design the pipes specifically for the map with thicker outlines and different lengths. While certainly possible, I have my doubts that this will be done anytime soon.

Suggestions?

Valete,
Quintus

**Comment by Quintus** [comment]
Here is a screenshot with the blue pipes replaced:

![pipes](http://team.secretchronicles.de/~quintus/stuff/pipes.png)

Valete,
Quintus

**Comment by datahead8888** [comment]
It certainly looks less Nintendo-ish.  @sydneyjd  - what do you think?

**Comment by Quintus** [comment]
I should probably just have continued with my work. Have a look at how it looks with all the pipes replaced:

![All pipes replaced](http://team.secretchronicles.de/~quintus/stuff/pipes2.png)

Valete,
Quintus

**Comment by Quintus** [comment]
This is now in `release-2.0.0` for anyone to try out. Actually I don’t think it looks bad anymore if you have all the pipes replaced.

Valete,
Quintus

**Comment by Quintus** [comment]
The current state is releasable, so I remove the “Blocker” label. Before closing I want some more opinions, though.

**Comment by sydneyjd** [comment]
No, they don't look bad at all.
I would have tried the pipes without the line, but these are fine also.

**Comment by DarkAceZ** [comment]
They look nice, but the last segment that goes into the ground would look better if it didn't have the black outline. The black outline on the bottom there kind of takes away from the illusion of the pipe going into the ground.
Also, I wonder how they'd look if they were just a little bit bigger, or wider at least.

**Comment by datahead8888** [comment]
As long as the pipes do not look Nintendo-ish and as long as they look reasonable, I propose we just go ahead and release as-is.  We seem to be reasonably at that point in my opinion.  We can always touch these up in a later release (if we haven't stripped them out yet).

We desperately need more contributors, which a release will help bring.  Even my recruiting efforts on forum sites will not be effective without a release.

**Comment by Quintus** [comment]
@DarkAceZ Yes, improvements are always possible. See #423 in this regard, or feel free to open another issue.

I close this now as the current state is releasable.

Valete,
Quintus
