### ISSUE TITLE
Specifying More Detailed Contributor Info in the Credits...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#433]
In authors.txt (the file used for the credits) is simply lists all people in broad categories.
It does not show the major role FluXy once had, that Quintus is the project leader, or that Luiji is the assistant project leader.  They are just "coders".

@Quintus said he changed it this way so that it would be easier to parse by the rake file that builds the credits cpp file.  We thus have two considerations:
1) Does everyone else agree that this extra information in the credits file is useful?  FluXy was worried about how we cite him in the project.  If we cannot get add this extra information due to parsing issues, we could find a creative way to add it to the details listed for each author (within parentheses or something).
2) We might consider what the options for the rake file process are in order to maintain more flexibility in the future.  Something else may come up with the credits, and we do not want to be limited.

On another note, Quintus has said the credits file should create a cpp file at compile time so that the credits is not a config file, which would literally be encouraging people to edit the credits when they download the game, which is not respective of the work of the contributors.  This point is valid, but it gives insight into our discussion.

**Comment by Quintus** [comment]
I am fine with more info in the credits file. It should be doable by simply adjusting the way the `Rakfile` generates the `credits.cpp` file from it.

Valete,
Quintus

**Comment by Quintus** [comment]
I've thought about this a little while working on the (now finished) CMake port of the credits.cpp generator. The authors.txt already suffers from a problem: most e-mail addresses in it are out of date. Nobody cares to update them; even the addresses in the Git commits are more recent.

I suggest to reject this feature request and instead remove the e-mail addresses from authors.txt. It is not possible to remove authors.txt entirely and read the author information from Git, because from the early days of TSC/SMC there are contributors without Git commits that only have a reference in authors.txt (though nobody probably knows what their contributions are).

**Comment by xet7** [comment]
@Quintus 

Yes, email addresses should be removed. Most likely they are not up-to-date. History can remain as it's currently.

**Comment by Quintus** [comment]
As nobody objects, I reject this feature request. Commit ce6a48e58a66fbb25efbe44ea76fc6cd1eaba425 restructures the credits to contain a little more information as was suggested by this ticket, but it also removes all the e-mail addresses. Additionally, it applies some style fixes.
