### ISSUE TITLE
New Battle Theme for Bonus Levels...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#449]
As brought up with @kirbyfan64 in http://forum.secretchronicles.de/topics/262 it might be helpful to have a new battle or challenge theme for bonus sub levels (bonus areas with scripting logic).

**Comment by kirbyfan64** [comment]
Out of curiosity, what would this sound like?

(I'm *technically* working on the tutorial song, which is fine for the first 5 measures, after which it keeps turning into a battle-sounding theme...)

**Comment by datahead8888** [comment]
It would probably sound like a "fun" song much like many of our level land music tracks but also have enough force and movement to show some competition going on.

The hammer brothers theme from Super Mario Bros. 3 accomplishes this, though obviously we need to come up with our own melodies to be original.

**Comment by Quintus** [comment]
@kirbyfan64 Many thanks you are still with us :-). When 2.0.0 is released very soon, there will be more time again to focus on assets.

On topic, I agree that we need some more theme-specific songs. Currently each level just uses what the author thought it fit, but we ought to set up a policy for certain levels and/or areas so that a uniform impression is created. A song specifically crafted for that purpose would ease things indeed.

Valete,
Quintus

**Comment by datahead8888** [comment]
> Currently each level just uses what the author thought it fit, but we ought to set up a policy for certain levels and/or areas so that a uniform impression is created.

We need to create an overarching set of level design guidelines, actually.  I'd suggest generally making them somewhat loose and not overbearing, while still encouraging some level of consistency and integration with story and sections of the game.

**Comment by datahead8888** [comment]
Submission by kirbyfan64: http://forum.secretchronicles.de/topics/339

**Comment by Bugsbane** [comment]
Yup. Consistency in the music is just as important as in the story or art design. Unfortunately, this is an area I know little about. :-/
