### ISSUE TITLE
tsc crashes in 1st world 1st lvl

### ISSUE THREAD

**Issue by gepavlo** [Secretchronicles/TSC#452]
Hi, I have Windows 8.1 and intel core 2duo@3.17 Ghz CPU, AMD RADEON 7770 GPU, 8 GB DDR3 RAM but when I start the game, it crashes at first level of the first world. It shows the map and Maryo in it but when I press ENTER the game crashes and the program stops working.
Thanks.

**Comment by kirbyfan64** [comment]
When you say "crashes", do you mean "it instantly closes"? Does anything get printing to the screen?

**Comment by gepavlo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14129671/9690416/e6fb2b96-5344-11e5-9b3d-f0daa1d482a3.jpg)

**Comment by gepavlo** [comment]
I managed to see this screen only on the rc1 version where the screen freezes for some time when you enter a stage in the map and after 20 seconds the game continues as normal. Then I pressed PrtScn and took this image.

**Comment by JohnTheTreeman** [comment]
I experience the exact same problem. Win7 64bit

**Comment by kirbyfan64** [comment]
Well, it seems "normal" that it freezes for several seconds when loading the level, but I'm still not sure about the crash. Smells like a segfault to me.

**Comment by Luiji** [comment]
@gepavlo Can you please start the version of TSC that's crashing from the Command Prompt and screenshot it after the crash? That way we can get the message for what's actually crashing. The screenshot you gave shows a normal session, though the freeze isn't normal.

I, sadly, don't know how to launch TSC from the command prompt on Windows. I know you can start the command prompt with Windows Key + R, type cmd, and press enter. Then you need to specify the path to TSC.exe in quotes and press enter. It should be something like `C:\Users\You> "C:\Program Files\The Secret Chronicles\TSC.exe"<enter key>` but you'll have to find the exact name on the file system.

**Comment by datahead8888** [comment]
@gepavlo, sorry for the slow response from the developers.  Some of us have been unavailable for a while for various reasons.  How consistently was the game crashing when you entered the first level on the map?  Did you do anything else like save your game?

If the game is pausing for a while when you enter a level, this is due to poor level loading time.  It probably still needs to be optimized.

On my Windows 8.1 system, the game is located at "C:\Program Files (x86)\TSC\bin\tsc.exe".  As Luiji said, you can run this from the command line in Windows.  

If you are getting a crash that terminates the entire game -- If you're up for it, info from the gdb debugger is what will most likely allow this to get fixed.  You could attempt to run gdb in Windows, using the MinGW project.  On my system gdb is at C:\MinGW\bin\gdb.exe.  The instructions at http://wiki.secretchronicles.de/Creating%20a%20GDB%20stacktrace explain how to provide the needed stack trace information from gdb.  If I remember correctly, Quintus believes gdb results will be better in Linux than Windows.  Thus if you can do this in Linux it may be more meaningful.  Otherwise, with enough info, the developers can try to do this when they get some time.

**Comment by datahead8888** [comment]
Here is a related post about the crash: http://forum.secretchronicles.de/topics/285
This posting also contains a video of the crash happening.

Lastly, I propose we mark this issue as "Blocker", since we need to fix it before the next release.  The game is unstable with crashes happening this frequently.

**Comment by Quintus** [comment]
Needless to say, I can’t reproduce this on Linux, and I know of people who reported 2.0.0 working fine on Windows. Thus, it must be something you have in common. I’ll make a guess completely out of nothing: @gepavio, do you have a username with special characters in it (i.e. non-ascii chars such as é, ö, î or whatever)?

@kirbyfan64 is correct, this appears to be a segfault or an exception. I can’t fix what I can’t reproduce, so I need more info.

Valete,
Quintus

**Comment by Quintus** [comment]
Typos for the world. @gepavlo, do you have a username with special characters in it (i.e. non-ascii chars such as é, ö, î or whatever)?

Vale,
Quintus

**Comment by Quintus** [comment]
Also, @gepavlo, can you start the game from the command prompt and post the output the window contains *after* the crash? See @Luiji’s instructions. Also, @JohnTheTreeman, please do the same (and report whether you have a non-ascii username).

Valete,
Quintus

**Comment by Quintus** [comment]
Also, please do not use screenshots of the commandprompt window. You can copy from the window by utilising the Shift key to my knowledge. Paste that here into a code block.

Valete,
Quintus

**Comment by Quintus** [comment]
Until #462 is resolved, this issue is blocked as it is impossible to debug. The other issue must be resolved first. I’m thus unassigning myself.

Valete,
Quintus

**Comment by Quintus** [comment]
I revoke what I said above. I just found that GDB understands the debugging symbols of the crosscompiler of the current version of MXE, which means I can now — **finally** — properly debug the Windows built of TSC.

I’m a bit too exhausted right now to investigate this bug, though. Maybe later.

You can find the updated crosscompilation instructions in the INSTALL.md file in the `devel` branch (they work for 2.0.0 as well).

Valete,
Quintus

**Comment by Quintus** [comment]
Okay. I have a Windows built of 2.0.0-final now, and it has debugging symbols, and my GDB can read them. However, I still cannot reproduce the issue, even on Windows. I need more reproduction information. Please give me more details:

* Do you have a username with non-ascii characters?
* Do you have a 32-bit or 64-bit OS? (I can only test with a 32 bit one)
* Does your TSC installation path have spaces in the directory name?

It’d be ideal if someone on whose system the game is crashing entered a debugging session in IRC with me.

Valete,
Quintus

**Comment by Quintus** [comment]
Okay, the binary from secretchronicles.de crashes for me as well

**Comment by Quintus** [comment]
@kirbyfan64 @JohnTheTreeman @gepavlo I think I traced it down to a bad binary, probably got corrupt during upload or moving between my computers. I recompiled 2.0.0 with the same settings as before (just used a newer crosscompiler) and I was unable to reproduce the crash with the resulting binary. So, could you three please uninstall what you have right now and instead install this program: http://team.secretchronicles.de/~quintus/stuff/new-tsc-2.0.0-win32/TSC-2.0.0-win32.exe

Please report back whether this crashes for you or not. If it does not crash, we’re likely to issue a 2.0.1 release just for this new binary, resulting in another new binary, which you should then test. 

If you know how to do it, please verify that the file you downloaded from the above link has this MD5 checksum: 6bc19c1bd835f7b25304f6f431af7de4 This ensures the file did not get corrupted during up- and downloads.

Valete,
Quintus

**Comment by gepavlo** [comment]
This version works fine for me. Thanks

**Comment by Quintus** [comment]
> This version works fine for me. Thanks

Glad to hear that. I replaced the faulty binary on our FTP server and wrote a news article for the website. The website’s front and download pages will show the information tomorrow.

Valete,
Quintus

**Comment by datahead8888** [comment]
In future releases, we'll need to be careful to compile release candidates in release mode so that people test the same version of the release that we intend to use.  The md5 checksum can be given to all testers, and we can then check this checksum on the server when posting the executable for download.

**Comment by Quintus** [comment]
This is not possible, because the executable needs to be recompiled when the version number is changed from e.g. 2.0.0-RC1 to 2.0.0. The version number is shown in the game on the start menu and in the output of `tsc --version`.

Vale,
Quintus

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:

> In future releases, we'll need to be careful to compile release
> candidates in release mode so that people test the same version of the
> release that we intend to use.  The md5 checksum can be given to all
> testers, and we can then check this checksum on the server when
> posting the executable for download.

This is not possible. The release candidate has a version like
2.0.0-RC1, which is reflected in the game both in the start menu
(bottom-right corner) and the output of `tsc --version`. Doing the final
release implies removing `-RC1` from the version number, which in turn
requires recompilation of the executable so it shows the correct version
strings in the main window and `--version` output.

Vale,
Quintus
