### ISSUE TITLE
Review new level background and map images...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#458]
@Bugsbane, @sydneyjd, @BodhiPeace

We have new artwork in the forums that needs to be reviewed.
 
Level background submission - http://forum.secretchronicles.de/topics/307
Map graphics submission - http://forum.secretchronicles.de/topics/305

We would like to get an artist to view these, especially in light of the WIP style guide at http://wiki.secretchronicles.de/StyleGuide

**Comment by Bugsbane** [comment]
Regarding the first one, i love them as works of art in their own right, and i think the general concept is heading in the right direction. There area couple of things that would be good to resolve to get it fitting in with the other artwork and to balance the level of visual dominance for a background object:

First, the combination of the size and high contrast on the stripes makes these draw a great deal of visual attention to the background, distracting the player. The larger something is, the more attention it tends to draw which, fit a background object needs to be balanced to keep the player focused on the interactive parts of the game. Reducing the contrast, particularly on darker colors would likely help. Fading the colors may, too although it would be nice to not lose the saturation/ vibrancy if we can find better ways. The size of the stripes, and that they're vertical also draw extra attention. While yellow is a happy, cheerful color, it is also very bright, which further makes these draw the players attention away from the gameplay, too.

You could attempt to fade the dark stripes down to something, say 25% opacity (or change their color closer to the lighter color), make them 1/4 the width, with two sets crossing over at 45 degrees rather than vertical.

Second, this is a completely 3D style where all of the other ingame graphics have a more 2.5D style (that is 2D with a single layer of highlights or shadows, sometimes with a gradient between). It also needs the "darker color" outline mentioned in the style guide. Both could still be achieved in blender by using freestyle, although if you're not familiar with freestyle, it may take more fiddling than just bringing the current images into Inkscape and using them as a guide to recreate them purely there. Freestyle is fun to play with though if you're inclined. ;P


The second set of images match very nicely. They just need to use the standard width outline with a non black color (as they're background objects, not player / enemy / interactive )

Nice work everyone. With the appropriate modifications, I'd love to see both in game.

**Comment by datahead8888** [comment]
@Bugsbane, is there a better way to reach you?  We had @'ed you on the forum, but to my recollection, you said the email addresses you associated with the forum and/or github are not ones you check.  Thus I'll probably need to repaste these suggestions to the other forum to make them seen, and by this point the people in that discussion may not be checking as frequently and may take a long time to respond to your feedback.

> Second, this is a completely 3D style where all of the other ingame graphics have a more 2.5D style

Could it be said that the gems have a 3D style already?  I know these were done in Blender, as were the coins/waffles they replaced.

**Comment by Bugsbane** [comment]
I've replied on the forums and updated my email. I'm still not likely to be on the forums much, as I'm extremely busy, but I'll try to help out on graphics related discussions where possible.

**Comment by Quintus** [comment]
Review has happened on the forums (links see OP), closing this ticket now.
