### ISSUE TITLE
Can't enter performance mode while in level editor

### ISSUE THREAD

**Issue by lambda-11235** [Secretchronicles/TSC#497]
I can't enter performance mode while in the level editor. This is because the binding for p is caught in in cEditor::Key_Down before ctrl-p is caught in cKeyboard::Key_Down.

**Comment by Quintus** [comment]
Taran Lynn <notifications@github.com> writes:

> I can't enter performance mode while in the level editor This is
> because the binding for p is caught in in cEditor::Key_Down before
> ctrl-p is caught in cKeyboard::Key_Down

I assume this report is against the devel branch, because in
feature-sfml-port2 there is no input handling available at all currently
(because I’m working on it in the separate branch sfml-port-input).

However, performance mode is a debugging detail that is not meant to be
used by end users (players) of the game. It is an unofficial and
undocumented feature that may be subject to change at any time without
notice. While your report thus is valid, it is unlikely that anyone is
going to fix that soon, given also that the workaround is to simply
disable the level editor, enable performance mode, and then enable the
level editor again. It may also happen that performance mode is just
removed entirely.

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
Performance mode is an internal detail not meant to be used publically. Closing, WONTFIX.
