### ISSUE TITLE
"Reload world" consistently causes segfault

### ISSUE THREAD

**Issue by Bugsbane** [Secretchronicles/TSC#523]
gdb output from opening TSC, starting campaign and choosing reload level:

Starting program: /opt/tsc/bin/tsc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Initializing Package Manager
[New Thread 0x7fffe400e700 (LWP 15124)]
[Thread 0x7fffe400e700 (LWP 15124) exited]
[New Thread 0x7fffe400e700 (LWP 15125)]
Warning: Unknown world object XML tag ''
Warning: Editor item could not be created: 

Program received signal SIGSEGV, Segmentation fault.
0x000000000077360c in TSC::cOverworld::Update() ()

I tried this on both world 1 and world 4 with a recent git clone.

**Comment by lambda-11235** [comment]
It seems that cOverworld::m_sprite_manager isn't being allocated properly. Its objects and m_uid_pool members both have ridiculous sizes, so it's the sprite manager that's misallocated, not just one of its members. The cOverworld appears to be properly allocated except for that member, although I haven't tested all it's members.

**Comment by Bugsbane** [comment]
I'd like to add that this is a pretty darn serious bug as it doesn't even "just" crash TSC. It actually takes hangs X on my Ubuntu system (possibly because I had TSC in full screen mode).

**Comment by kirbyfan64** [comment]
@Bugsbane 

> (possibly because I had TSC in full screen mode)

Yeah, that'll do it...

**Comment by Quintus** [comment]
This bug is the very essence of TSC’s horrible legacy code architecture. There are several global objects involved that are occasionally also used as member variables. It is just horrible to debug, I just tried it.

**Comment by Quintus** [comment]
> It seems that cOverworld::m_sprite_manager isn't being allocated properly.

No. `cEditor_World::Function_Reload()` *deletes* the currently active overworld, without noticing it. This is because the active overworld is a global pointer (`pActive_Overworld`), but the very same pointer is also used as a member variable `m_overworld` in `cEditor_World`. `cEditor_World::Function_Reload()` now deletes `m_overworld` (== what the global pointer points to), but does not adjust the global `pActive_Overworld` pointer, which thus now points to deallocated memory. In the next run of the game’s main loop, `pActive_Overword` is used to update the current overworld, however, because `pActive_Overworld` now points to deallocated memory, it crashes with a segmentation fault.

And no, just setting `pActive_Overworld` to the new overworld in `cEditor_World::Function_Reload()` is not sufficient to fix the bug, because then it crashes at a different point where you then notice that the deallocated sprite manager member of the global overworld pointer has been used as the member variable of another object that now wants to be updated. I gave up debugging at this point because the code was so horrible.

If you ever wanted to take a look at what happens if you violate the secrecy principle and combine that with global variables, this bug is a really nice example for this. There might be workarounds to get it to work (namely updating all the member variables that point to some global pointers somewhere), but the real “fix” is to redesign the code architecture.

Valete,
Quintus

**Comment by Quintus** [comment]
Did I mention the mouse cursor class contains a copy of the overworld’s sprite manager pointer? If this appears insane to you, then I acknowledge you that it is.

**Comment by Quintus** [comment]
The “correct” solution that does not change TSC’s code architecture is to rewrite `cEditor_World::Function_Reload()` to use the world manager (`pOverworld_Manager`). Currently, the function tries to cheat the overworld manager by swapping out the overworld without thinking about all the other objects that might be affected. Instead, it should remove the current world from the overworld manager, reload it from the world dir, add the newly loaded world to the world manager, and then **advise the world manager to set that world active** instead of trying to do it itself. The world manager alone has the knowledge of all the objects that might be affected by such a change.

Still, the code architecture is awful. Why does the world manager need a sprite manager, also?

Valete,
Quintus

**Comment by Quintus** [comment]
The bug is not related to campaigns as the OP suggests. It can be reproduced by these steps:

1. Start TSC
2. Click "Start"
3. Switch to the "World" tab
4. Select "World 1" and enter it
5. Press F8 to open the world editor
6. On the left side, click the "Reload" entry
7. Answer the confirmation question with "yes"
8. Segfault.

Valete,
Quintus
