### ISSUE TITLE
Game stutters when acquiring and losing the lemon powerup

### ISSUE THREAD

**Issue by lambda-11235** [Secretchronicles/TSC#549]
The game pauses for about 1 second when I gain or lose the lemon powerup. I tested this on the eatomania level.

**Comment by Quintus** [comment]
I have seen this as well. Not sure what causes it, though.

Vale,
Quintus

**Comment by Quintus** [comment]
Okay, I found the culprit. @kirbyfan64 sets the main thread to sleep when loading a new music [in audio.cpp](https://github.com/Secretchronicles/TSC/blob/8a2d356749867631e3b842b1dedc02075df1932e/tsc/src/audio/audio.cpp#L377).

~~~~~~~~~ c++
            while (m_music->getVolume() < current) {
                // sleep for several milliseconds
                boost::this_thread::sleep_for(boost::chrono::milliseconds(int(fadein_ms / count)));
                // raise the volume
                m_music->setVolume(int(m_music->getVolume()+count));
            }
~~~~~~~~~

Calling a sleep function in a single-threaded application isn't such a good idea. @kirbyfan64, can you fix that please?

Vale,
Quintus

**Comment by kirbyfan64** [comment]
Whoops, I thought that `Mix_FadeInMusic` had blocked the calling thread, and therefore assumed that this was being called in a separate thread...

Unfortunately, I doubt the fix is going to be that clean or ideal, since the sound source would have to store both the fading thread and an atomic value to check the fading state. Here's my plan:

1. Create a class `FadableSoundSource` that looks like this:

    ```c++
    class FadableSoundSource : public sf::SoundSource {
        // A bunch of methods here for fading and stuff.
    };
    ```

2. Add a template class `FadableSoundModifier`:

    ```c++
    template <typename T>
    class FadableSoundModifier: public FadableSoundSource, T {
        using T::T;
    };
    ```

3. Replace `sf::Sound` and `sf::Music` with `FadableSoundModifier<sf::Sound>` and `FadableSoundModifier<sf::Music>`, respectively.

As ugly as that is, the only other solution I can think of would be to replace step 2 with some custom classes:

```c++
class FadableSound : public FadableSoundSource, public sf::Sound {
    using sf::Sound::Sound;
};

class FadableMusic : public FadableSoundSource, public sf::Music {
    using sf::Music::Music;
};
```

and modify step 3 accordingly. However, this ends up being basically the same thing, except slightly more verbose.

Of course, we could always use a hash table of fading data, indexed by a pointer to a sound source, but I don't think you'd like that very much... ;(

**Comment by Quintus** [comment]
Well, you could leverage the horrible Game_Action_Data system in TSC (you know, that one that uses in-memory XML; see `core/game_core.cpp`) and implement a new `Game_Action_Data_Middle` parameter that gets checked in the main loop and adjusts fading.

Or we could disable fading alltogether.

Vale,
Quintus

**Comment by kirbyfan64** [comment]
> Well, you could leverage the horrible `Game_Action_Data` system in TSC (you know, that one that uses in-memory XML; see `core/game_core.cpp`) and implement a new Game_Action_Data_Middle parameter that gets checked in the main loop and adjusts fading.

Uhhh...in-memory XML... why...oh, why...

> Or we could disable fading alltogether.

Honestly, I really think that isn't a bad idea, or at least until we ditch that weird `m_music_old` thing.

**Comment by datahead8888** [comment]
> Or we could disable fading alltogether.

I haven't had a chance to read the options listed above closely.  If it was working before the SFML port, I would suggest filing it as a bug; otherwise it's arguably a feature.  If we don't have time to change it before the release, we could release without it and file a ticket to change it in a later release if a bug.

If it was working before, I think we should fix it eventually -- we have already lost the title theme, turtle boss, and image previewing (removed by FluXy a long time ago) features before.  I realize we gained a ton of features with version 2.0, but I still view losing features as a step backwards.

**Comment by kirbyfan64** [comment]
What if fading is enabled on music but disabled on sounds? I've never heard a "sound" fade-in or fade-out; usually, it's just super-short, and any volume changes are within the sound itself.

This would make it 100% feasible to implement without the weird things I mentioned above.

**Comment by Quintus** [comment]
On Mon, Aug 08, 2016 at 01:56:35PM -0700, Ryan Gonzalez wrote:
> What if fading is enabled on music but disabled on sounds? I've never
> heard a "sound" fade-in or fade-out; usually, it's just super-short,
> and any volume changes are within the sound itself.

Sounds okay to me.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
If we have never noticed fading on sounds, disabling it for them makes sense.
It might make sense to verify if fading worked for music to begin with, though if it was broken, this might have been a bug.
