### ISSUE TITLE
Issues building mruby with CMake's Ninja backend

### ISSUE THREAD

**Issue by kirbyfan64** [Secretchronicles/TSC#559]
Needless to say, trying to build TSC today left me with several ["Mrgrgr"](http://www.siliconera.com/wordpress/wp-content/uploads/2015/06/3DS_BravelySecond_JuneDirect_SCRN_03_thumb.png) moments...

The CMake integration with mruby is kind of screwy, mostly if I build in a separate directory. Case in point:

1. Run `mkdir build && cd build && cmake -G Ninja ..`.
2. Run `ninja`. For me, this resulted in `ninja: error: 'mruby/build/host/lib/libmruby.a', needed by 'tsc', missing and no known rule to make it`. Apparently, even though mruby *had* been built *outside* the build directory, TSC wanted it *inside*. Fixed via `cp -r ../../mruby/mruby/build mruby` in the build directory.
3. Now I'm getting:

    ```
[1/167] Performing build step for 'mruby'
FAILED: mruby-prefix/src/mruby-stamp/mruby-build 
cd /media/ryan/stuff/TSC/tsc/build/mruby && ./minirake MRUBY_CONFIG=/media/ryan/stuff/TSC/tsc/mruby_tsc_build_config.rb CROSSCOMPILE_TARGET= && /media/ryan/stuff/Downloads/cmake-3.6.0-Linux-x86_64/bin/cmake -E touch /media/ryan/stuff/TSC/tsc/build/mruby-prefix/src/mruby-stamp/mruby-build
(in /media/ryan/stuff/TSC/tsc/build/mruby)
rake aborted!
Don't know how to rake /media/ryan/stuff/TSC/mruby/mruby/src/re.h
    ```

    So now the build system it's running the mruby in the build directory and trying to build a file *outside* the build directory. I've been searching for more on this, but I can't find anything. I don't know of any build steps that require a `re.h`. To fix it, I did ` cp mruby/include/mruby/re.h ~/stuff/TSC/mruby/mruby/src/re.h`.

Now I'm on the worst one *yet*:

```
[1/165] Performing build step for 'mruby'
FAILED: mruby-prefix/src/mruby-stamp/mruby-build 
cd /media/ryan/stuff/TSC/tsc/build/mruby && ./minirake MRUBY_CONFIG=/media/ryan/stuff/TSC/tsc/mruby_tsc_build_config.rb CROSSCOMPILE_TARGET= && /media/ryan/stuff/Downloads/cmake-3.6.0-Linux-x86_64/bin/cmake -E touch /media/ryan/stuff/TSC/tsc/build/mruby-prefix/src/mruby-stamp/mruby-build
(in /media/ryan/stuff/TSC/tsc/build/mruby)
CC    build/host/mrbgems/mruby-compiler/core/y.tab.c -> build/host/mrbgems/mruby-compiler/core/y.tab.o
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y: In function ‘parser_yylex’:
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y:5280:14: error: implicit declaration of function ‘mrb_reserved_word’ [-Werror=implicit-function-declaration]
         kw = mrb_reserved_word(tok(p), toklen(p));
              ^~~~~~~~~~~~~~~~~
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y:5280:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         kw = mrb_reserved_word(tok(p), toklen(p));
            ^
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y:5284:25: error: dereferencing pointer to incomplete type ‘const struct kwtable’
           p->lstate = kw->state;
                         ^~
cc1: some warnings being treated as errors
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y: In function ‘parser_yylex’:
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y:5280:14: error: implicit declaration of function ‘mrb_reserved_word’ [-Werror=implicit-function-declaration]
         kw = mrb_reserved_word(tok(p), toklen(p));
              ^~~~~~~~~~~~~~~~~
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y:5280:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         kw = mrb_reserved_word(tok(p), toklen(p));
            ^
/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core/parse.y:5284:25: error: dereferencing pointer to incomplete type ‘const struct kwtable’
           p->lstate = kw->state;
                         ^~
cc1: some warnings being treated as errors
rake aborted!
Command Failed: [gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -g3 -O0 -DMRB_UTF8_STRING -DMRB_DEBUG -DMRBGEM_MRUBY_COMPILER_VERSION=0.0.0 -I"/media/ryan/stuff/TSC/tsc/build/mruby/include" -I"/media/ryan/stuff/TSC/tsc/build/mruby/mrbgems/mruby-compiler/core" -MMD -o "/media/ryan/stuff/TSC/tsc/build/mruby/build/host/mrbgems/mruby-compiler/core/y.tab.o" -c "/media/ryan/stuff/TSC/tsc/build/mruby/build/host/mrbgems/mruby-compiler/core/y.tab.c"]

ninja: build stopped: subcommand failed.
```

:O

**Comment by kirbyfan64** [comment]
This seems to work normally with the makefile backend of CMake, so I think it's all when using Ninja.

**Comment by kirbyfan64** [comment]
Oh, and now I can't manage to install CEGUI 0.8...despite trying multiple `.deb` packages...

This is going to be a while. :(

**Comment by Quintus** [comment]
Maybe you should cease use of an unsupported building backend :-)

mruby is included in TSC as Git submodule, which recently has been updated. So please ensure you ran `$ git submodule update` before going any further. mruby cannot be built out of its own source tree (limitation of its build system), so I decided to trick it into doing that, because previously the TSC build system was building mruby really in the mruby submodule directory, which is part of the sources and should not contain binary stuff as it makes it difficult to clean and is confusing when the user explicitely asked to not build TSC in its source tree. I do this by having CMake copy the entire mruby directory into `CMAKE_BINARY_DIR` in the "download" step and then have CMake invoke the `rake` command (mruby's build system) there so that it looks to mruby as if it was build in its source tree. Copying happens through CMake's magic `cmake -E` functionality so is done platform-independant. Finally, to ensure the required headers are found, an `-I` option is passed via cmake's `include_directories` that points to `${TSC_SOURCE_DIR}/../mruby/mruby/include`, which is guaranteed to exist regardless of whether TSC is build inside or out of source.

Since `ninja` is an unsupported build system, I'm afraid you're on yourself here. The relevant CMake code is in the file `tsc/cmake/modules/ProvideMRuby.cmake`, with the `include_directories` call amongst all others in the main `CMakeLists.txt`. If you find a solution to the problem, you can of course push it.

Vale,
Quintus

**Comment by Quintus** [comment]
Oh, and if you have a compiled pre-update mruby lying around in the submodule directory, please clean it.

~~~~
$ cd tsc/mruby/mruby
$ rake clean
~~~~

Otherwise the build system, which as explained now uses this copying trick, may get confused.

Vale,
Quintus

**Comment by kirbyfan64** [comment]
> Maybe you should cease use of an unsupported building backend :-)

Well, considering Ninja is used by Chrome, LLVM, and Android, I'd say it's getting pretty popular... ;)

> Oh, and if you have a compiled pre-update mruby lying around in the submodule directory, please clean it.

...that may actually be the issue. I'll try it next chance I get. Of course, now I still need to figure out why my CEGUI 0.8 installation has mission headers... :/

**Comment by Quintus** [comment]
On Sat, Aug 06, 2016 at 07:31:10AM -0700, Ryan Gonzalez wrote:
> now I still need to figure out why my CEGUI 0.8 installation has
> mission headers... :/

As long as they aren't mission-critical that's okay.

You may bug xet7 if you have questions. He compiled TSC on Lubuntu. You
should join IRC more often anyway :-)

Thanks to xet7's efforts, there's also a file documenting the install
process for Lubuntu in tsc/docs/pages. Maybe that helps you.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by kirbyfan64** [comment]
> As long as they aren't mission-critical that's okay.

Dang it, I mean "missing". And, yeah, they kind of were, considering the OpenGL renderer target was entirely missing... I managed to also [find a bug in the CEGUI build system](https://bitbucket.org/cegui/cegui/issues/1136/cegui-08-cmake-files-do-not-link-to-the).

Also, when I ran `rake clean` (after installing rake), then I ended up with:

```
ryan@DevPC-LX /media/ryan/stuff/TSC/tsc/build devel $ ninja
ninja: error: 'mruby/build/host/lib/libmruby.a', needed by 'tsc', missing and no known rule to make it
ryan@DevPC-LX /media/ryan/stuff/TSC/tsc/build devel $
```

I ran this to fix it:

```
cp -r ../../mruby/mruby mruby
cd mruby/mruby
clmake # An alias for: make CC=clang CXX=clang++
cd ..
ln -s $PWD/mruby/build build
cd ..
```

Now, it seems to be working!!

**Comment by kirbyfan64** [comment]
Spoke too soon. :( Now I have linker errors for pretty much every single CEGUI function.

**Comment by kirbyfan64** [comment]
YESSS!! Got it to build! Turns out, CEGUI 0.7 was still installed. Deleted it caused it to link against 0.8!

**Comment by datahead8888** [comment]
I had to apply a patch to SFML's CMake configuration when building it from source in order to deal with a bug in g++ itself, so I know what this sort of experience is like :)

**Comment by Quintus** [comment]
> (after installing rake)

Well, you could also have used `./minirake clean` as mruby ships its own mini version of Rake :-)

> ninja: error: 'mruby/build/host/lib/libmruby.a', needed by 'tsc', missing and no known rule to make it

Which is correct, since that file is an output of the `mruby` virtual target (as well as `libmruby_core.a`). Once the `mruby` virtual target is built, the file is available. Seems the `ninja` generator doesn't get the dependencies right and wants to link tsc before the mruby target is run (which would have copied the `mruby` directory there and then built these files). The `mruby` target however is explicitely marked a dependency of `tsc` via `add_dependencies()`, so it should have honoured that. Maybe a bug in CMake?

Vale,
Quintus

**Comment by kirbyfan64** [comment]
@Quintus Found [this](https://cmake.org/pipermail/cmake/2015-April/060233.html), which confirmed my suspicions. While make checks dependencies as it runs, Ninja generates the whole DAG ahead of time, and it has no way of knowing that the mruby target produces that library. The solution was:

> Try adding the following to your ExternalProject_Add call:
>     BUILD_BYPRODUCTS ${HIDAPI_ROOT}/bin/lib/libhidapi.a

> This is required so that the ninja generator knows which target produces the named output.

**Comment by Quintus** [comment]
I have adjusted the call to `ExternalProject` accordingly. Would you mind to test if this resolves your problem?

So far, I haven't seen any problems with building with `make` with this change, so from my part, it is okay.

Vale,
Quintus

**Comment by kirbyfan64** [comment]
Looks like it works now!
