### ISSUE TITLE
Jumping up from a ladder is quite confusing

### ISSUE THREAD

**Issue by akien-mga** [Secretchronicles/TSC#570]
Just built the current HEAD and tried the first level of the TSC campaign, but I quickly ended up stuck:
![tsc-stuck](https://cloud.githubusercontent.com/assets/4701338/19215899/cdd58e6c-8daa-11e6-9ee3-2ece1981a260.png)

I went down the ledge onto the ladder to explorer this part, and noticed that I couldn't go up again (at least none of keys and combinations I tried seemed to allow it).

It's when testing again while writing this issue that I finally found out that it _is_ possible to jump up from the ladder onto the platform. One needs to press "jump" **without** pressing up. While going up the ladder with the "up" key, it did not came to me that I would have to let it go to be able to jump, and thus I was always trying "up held + jump pressed", which doesn't work.

I'd suggest to allow jumping while holding the up key. Alternatively, if the current behaviour is preferred, some hints in the first level could help making the controls clearer (e.g. when on the ladder below the ledge, show a hint telling the user to press "jump").

**Comment by akien-mga** [comment]
BTW I've noticed that my terminal was spammed with:
```
Warning: Unknown key received, treating as CEGUI::Key::Unknown.
Warning: Unknown key received, treating as CEGUI::Key::Unknown.
```
That might be related? I'll gladly test further if need be.

**Comment by Quintus** [comment]
> Warning: Unknown key received, treating as CEGUI::Key::Unknown.

These warnings are normal and will be fixed by the time of the next release. SFML is more detailed about reporting keypresses to TSC's input handlers than SDL.

> It's when testing again while writing this issue that I finally found out that it is possible to jump up from the ladder onto the platform. One needs to press "jump" without pressing up.

I agree that that's a little unfortunate. I think it should be changed.

Vale,
Quintus

**Comment by datahead8888** [comment]
What a coincidence.  I just fixed a game controller bug with this.  The keyboard was enforcing the behavior you described while the game controller was not enforcing it.

The line of code in question is here:
https://github.com/Secretchronicles/TSC/blob/0f14d55e52c50db8651494e3359961a521da148b/tsc/src/level/level_player.cpp#1135:1137

Whichever way we decide to do it, we must maintain consistency between the keyboard and game controller behavior.  Preventing jumping while climbing normally would be reasonable, but on the rope below the slider in your screenshot it does not work so well.

That slider platform is going to be quite infamous - I spent a while debugging why you could not press down with the game controller to fall into the rope, only to discover a different, inconsistent keyboard/joystick issue :)

**Comment by datahead8888** [comment]
I have a tentative solution coded for this.  I was looking at making it so that Alex cannot jump while climbing (the current rule) unless he is at the very top, in which case it is allowed.

This would in turn work well with the solution I was looking at for analog jumping on climbing surfaces.  You obviously cannot both climb and analog jump at the same time.  I was thinking the player would normally climb if pressing up on the analog stick but jump if he lets it go at the very top and then pressed up again on the analog stick.

**Comment by Quintus** [comment]
On Sun, Nov 13, 2016 at 02:41:48AM -0800, Chris Jacobsen wrote:
> I have a tentative solution coded for this.  I was looking at making
> it so that Alex cannot jump while climbing (the current rule) unless
> he is at the very top, in which case it is allowed.

I am happy jumping while climbing pretty often. Some levels (I can't
just remember which ones) even have obstacles on climbing objects that
require you to jump around them to continue climbing. Usually these are
not in the normal level path, but bring you to a bonus area.

Here's how that typically looks, in nice ASCII art:

          ----- <--- Bonus area platform

        ^ <--- Top of ladder
        |
        * <--- Object in way (may also be an enemy, e.g. gee)
        |
        |
     ---+--- <--- Bottom

Another typical situation is jumping from one climbable object to
another climbable object in order to cross some kind of abyss, i.e.:


     ---------------------- <--- Ceiling
        |      |    |       <--- Ropes or similar hanging down
        |      |    |
     ----              ---- <--- Floor
           (Abyss)

That can be part of an ordinary, though more thorogh level even in its
regular path.

How do you want to solve the problem that the climbable object ends
directly on a massive platform over it? You cannot get off it other than
climbing down again with your approach.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
> How do you want to solve the problem that the climbable object ends directly on a massive platform over it? You cannot get off it other than climbing down again with your approach.

I don't follow what you're saying here.  How would you currently get around it with what is in devel now?

**Comment by Quintus** [comment]
On Sun, Nov 13, 2016 at 09:01:48AM -0800, Chris Jacobsen wrote:
>> How do you want to solve the problem that the climbable object ends
>> directly on a massive platform over it? You cannot get off it other
>> than climbing down again with your approach.
>
> I don't follow what you're saying here.  How would you currently get
> around it with what is in devel now?

You just need to be a little quick with your fingers. You can jump off
e.g. a rope, press the right key, and while still jumping and pressing
the jump key, press the left direction key. Alex will make an upwards
half circle in the air (totally realistic...) and come to stand on top
of the object that was blocking your way.

This of course assumes there is only a single massive block in the way
above you. If there is an entire ceiling with no holes, you cannot jump
through it obviously, since it is massive.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
I implemented this the way @Quintus and @akien-mga suggested.

One effect of this is that if you hold up while climbing a climbable object, jumping repeatedly, you will effectively "jump up" the object.  This is actually a kind of fun mechanic to manipulate. 

Give it a test run, and feel free to offer further suggestions.
