### ISSUE TITLE
Switch States Do Not Automatically Save/Load in Levels...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#579]
Steps to reproduce:
* Instance 1
   * Load cave_1_upper.tsclvl
   * Observe the relevant switch code (code set 1 below).  You will see that it is using the current method for switch actions.  It also has no save/load logic in the rest of the script.
   * Jump on the switch at the start of the level.
   * Save your game
   * Load your game
   * Observe the switch again.  You will find it is no longer pressed.  It did not save automatically.
* Instance 2
    * Load quintus_5_sub.tsclvl
    * Observe the relevant switch code (code set 2 below).  You will see that it is using the current method for switch actions.  It also has no save/load logic in the rest of the script.
     * In the level editor modify Alex's position so that he is next to the switch, and save the level
     * Begin playing the level.  Jump on the switch.
     * Save your game
     * Load your game
     * Observe the switch again.  You will find it is no longer pressed.  It did not save automatically.

I have also observed this in a working copy of my own Desert Break In level.
See also: http://forum.secretchronicles.de/forums/2/threads/2897

cave_1_upper.tsclvl relevant code:
~~~~~~~~~~~~~~~~~~~~~
pow1 = UIDS[503];
~~~~~~~~~~~~~~~~~~~~~
...
~~~~~~~~~~~~~~~~~~~~~~
Std::Switch.new(pow1) do
      bridge_of_blocks.each {|i|; i.enable; i.hide;}
      jewels.each{|i| i.enable};
      sign_go.enable;
      sign_death.disable;
      pe_poof.emitter_time_to_live = 1;
      enabling = true;
      Timer.after(1000) { enabling = false; enabled = true }
      Timer.after(3000) { disabling = true; }
      Timer.after(5000) do
        bridge_of_blocks.each{|i| i.disable};
        jewels.each{|i| i.disable};
        Audio.play_sound("item/mushroom_ghost.ogg");
        sign_down.enable;
        disabling = false;
        disabled = true;
      end
      Audio.play_sound("item/mushroom_ghost.ogg")
    end
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

quintus_5_sub.tsclvl full code:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TSC.require "std/switch"
TSC.require "std/enable"

Std::Switch.new(UIDS[398]) do
  UIDS[541].disable
  UIDS[540].disable
  UIDS[410].disable
end
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Quintus** [comment]
This is actually intentional, due to a limitation of the save/load events that causes problems when multiple event handlers are registered for these. The problem is described in the documentation for these events: http://www.secretchronicles.de/docs/2.0.0/core/levelclass.html

This is thus not a problem with the switches, but it is a feature request with regard to the save/load events to remove that limitation and subsequently use the newly implemented facility to improve switch handling.

It has to be noted, though, that Std::Switch cannot know what your switch does. It cannot restore more than the switch's state itself (pressed or not). If your switch removes a wall for example, the level designer has to add a load event that checks the switch's state and removes the wall on level loading as well.

Some switches, like the one in `cave_1_upper`, probably should not be saved at all, because they are focusing on a rather short timespan.

Vale,
Quintus

**Comment by Quintus** [comment]
This is not a bug, this is a feature request. Changing tags.
