### ISSUE TITLE
Editor: problems editing world maps

### ISSUE THREAD

**Issue by Skarfester** [Secretchronicles/TSC#596]
**2.1.0-dev**
When editing a level I can drag items from the menu normally, but I can't do that when editing a world (stock world or one created by me).
I can move the existing items in the world.

**Comment by Quintus** [comment]
I was pretty sure @datahead8888 fixed that a while ago... datahead, what do you think?

**Comment by Quintus** [comment]
@Skarfester Please post the exact output of `tsc --version`, which should include a commit ID if the builder did things properly. 2.1.0-dev refers to such a large range of commits that it doesn't really help.

**Comment by Skarfester** [comment]
`tsc -v` just says 2.1.0-dev. The .deb package is tsc_2.1.0+git20160813-1_amd64.deb, the one from TSC website.
Sorry, I though this was the last version.

**Comment by Skarfester** [comment]
Building TSC from source solves the initial dragging problem, but I found some more so I keep this issue open:

- Some objects cannot be selected with the pointer. For example, if I put the piramid or one of the old clouds, I cannot select, drag or delete them. If I make an area selection with the pointer I can delete this items with DEL, though.
- The path lines for moving Alex through the waypoints are invisible, making impossible to edit or add new ones.
- When making an area selection I cannot exit this mode by clicking; the selection area remains active until I click several times or hit some keys.
- Sometimes the right properties dialog remains active even when clicking back in the map.

**Comment by datahead8888** [comment]
@Quintus or @sauer2 - can you speak to the world editor problems Skarfester reported?  I am not as familiar with the world editor, so you might be in a better position to evaluate it.  I would probably need to compare against behavior in release 2.0 in Windows when I get some time in order to be sure on some points myself.

**Comment by datahead8888** [comment]
Once we confirm the issues, we'd probably want to rank them on priority so that we can get people editing worlds again.

**Comment by sauer2** [comment]
@datahead8888 Last time I even opened TSC shortly must be more than a half year ago; I don't remember anything, sorry.
Also, TSC requires Ubuntu 16.10 now, does it? I'd prefer to stay with LTS...

And to be honest, I don't have neither time nor interest in creating new levels and should probably leave the TSC team.

**Comment by Quintus** [comment]
On Wed, Jan 18, 2017 at 08:37:00AM -0800, sauer2 wrote:
> Also, TSC requires Ubuntu 16.10 now, does it? I'd prefer to stay with
> LTS...

It should work on the LTS, but the problem is that the Ubuntu people
need to backport this bugfix before it will work on the current LTS:
https://bugs.launchpad.net/ubuntu/+source/cegui-mk2/+bug/1608114

> And to be honest, I don't have neither time nor interest in creating
> new levels and should probably leave the TSC team.

This is sad to hear, but it of course is your decision.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by sauer2** [comment]
> It should work on the LTS, but the problem is that the Ubuntu people need to backport this bugfix before it will work on the current LTS: https://bugs.launchpad.net/ubuntu/+source/cegui-mk2/+bug/1608114

Well, that rules out a quick fix.

Anyway, godspeed, folks.

**Comment by Quintus** [comment]
Nice finds.

> Some objects cannot be selected with the pointer. For example, if I put the piramid or one of the old clouds, I cannot select, drag or delete them. If I make an area selection with the pointer I can delete this items with DEL, though.

This problem is not specific to the world editor; it also appears in the level editor. It's caused by an invisible CEGUI window in the upper third of the screen that houses the HUD (the HUD window is quite a bit taller than the visible HUD elements). I.e. your clicks and mouse moves are eaten by the HUD and never hit the actual level elements.

Hiding the HUD while the editor is active solves the problem (I just tested), but also prevents the element names to show up at the top. Fixing that requires some GUI re-arrangement.

> When making an area selection I cannot exit this mode by clicking; the selection area remains active until I click several times or hit some keys.

This is the same problem.

> Sometimes the right properties dialog remains active even when clicking back in the map.

This is the same problem.

> The path lines for moving Alex through the waypoints are invisible, making impossible to edit or add new ones.

The problem should by now be fixed. I remember having fiddled with the path lines' Z positions.

**Comment by Quintus** [comment]
> Fixing that requires some GUI re-arrangement.

I think I'm going to introduce a status bar to the editor. It can host all the information that is currently given through the popups (which are currently part of the HUD) and the mouse cursor (coordinates, UID, etc.). With the large popup out of the way, the problem should go away. Also, editing probably becomes easier.

**Comment by Quintus** [comment]
So, all the problems outlined in this ticket have finally been fixed. I have implemented the status bar today as promised, and I think it not only fixes the problems, but it also gives a much better user experience than the use of the HUD and the mouse cursor for conveying information before.
