### ISSUE TITLE
stating goals

### ISSUE THREAD

**Issue by jubalh** [Secretchronicles/TSC#611]
```
Note this is not merely a continuation of SMC, but we have our own goals and design principles we are slowly integrating into both the codebase and the artwork.
```
And what are does goals? What are the differences?

**Comment by datahead8888** [comment]
Short Term Goals:
* Finish release 2.1, introducing the SDL to SFML API port, Cegui API upgrade, and a number of new features
   * Need to fix an acceptable number of bugs (most of which are from the SFML/Cegui ports)
   * Need to introduce a replacement for the turtle boss that was removed in version 2.0
* Continue making the game look like less of a Mario clone
    * Make any further graphics / sound effect changes as needed
    * Introduce game mechanics changes as needed and currently feasible

Long Term Goals
* Rewrite the general game architecture - we've discussed both a complete rewrite and an incremental rewrite.  The team is currently leaning toward an incremental one.  Some of the code we inherited is fairly bad and slows down progress.
* Move toward a unique direction in game mechanics, paying homage to classic platformers but not being overly based on any given game
* Finish developing an immersive story that appeals to both adults and children

Current Differences:
* SMC still looked a lot like a Mario clone in many ways, and TSC tries to look like its own game.  We also changed the name of the hero from Maryo to Alex.  These changes are already very visible.
* We already have a good number of features not in the SMC series - level scripting, new enemies such as Pip, Beetle Barrage, and Doom Larry, crates, new levels, secret areas, and alternate level exits.

Planned Differences:
* SMC had an extremely thin story, while we hope to have an immersive story eventually
* As more game mechanics changes are introduced, many aspects of the game may change drastically.  For example, we have talked about introducing a life meter for the hero.

As I noted in another discussion, we are short on developer time -- we need more programmers and artists.  If you know anyone who might want to contribute, let us know; otherwise the game is probably going to move slowly for a while.

**Comment by Quintus** [comment]
Probably cleared :-P
