### ISSUE TITLE
Game window size is screwed up under a tiling window manager

### ISSUE THREAD

**Issue by kirbyfan64** [Secretchronicles/TSC#622]
![tsc](https://user-images.githubusercontent.com/1690697/35417094-7a5939b6-01f1-11e8-923c-c63eb9feba53.jpg)

Uhhh...

**Comment by kirbyfan64** [comment]
Also, I'd like to ask what that platform is doing in the tutorial level anyway. As evidenced by the screenshot, not all the collision is present to begin with, and it seems impossible to reach that platform. Or, at least, why the hell is that enemy there!?

**Comment by kirbyfan64** [comment]
The level selection screen is overly stretched, too:

![tsc-sel](https://user-images.githubusercontent.com/1690697/35417128-a95d0f80-01f1-11e8-9422-ccb7ec099d43.jpg)

**Comment by kirbyfan64** [comment]
FWIW manually setting the resolution seems to help fix the options menu, though now the characters were stretched:

![tsc-res](https://user-images.githubusercontent.com/1690697/35417188-f43c7482-01f1-11e8-964c-b5bba1c1bb82.jpg)

**Comment by kirbyfan64** [comment]
I'm still a little confused on one thing, though: shouldn't this be handled by TSC as a normal resize event? The first part in particular feels more like the window size was misread than anything else.

(FWIW I actually use GNOME now, ironically enough.)

**Comment by Quintus** [comment]
Am 07. Juni 2018 um 18:10 Uhr +0000 schrieb Ryan Gonzalez:
> I'm still a little confused on one thing, though: shouldn't this be
> handled by TSC as a normal resize event? The first part in particular
> feels more like the window size was misread than anything else.

Actually, TSC shouldn't support resizing the window. I think I set SFML
up in such a way that it tells the WM to not allow resizing.

> (FWIW I actually use GNOME now, ironically enough.)

And I'm still happily using i3 :-). Couldn't imagine a better window
manager. Every time I have to work on a Windows system I get crazy
because I have to do everything with the mouse.

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
I still don't think this is a bug, but a user issue. Closing. Reopen if you have strong feelings about this.
