### ISSUE TITLE
wrong aspect ratio for resolution like 2560x1080

### ISSUE THREAD

**Issue by boospy** [Secretchronicles/TSC#636]
Hello, 
i've installed gitversion on KDE-Neon 18.04. Really nice work :+1:  The only one problem what i've noticed is that there is an wrong aspect ratio with 16:10, 16:9.... for example 1280x800, 1440x900.... 
Is there a way in settings? Or is this a bug?

Greetings boospy

**Comment by xet7** [comment]
It could be bug, and most likely will not be fixed for TSC2 (this repo).

Resolution will be different for TSC3 https://github.com/Secretchronicles/TSC3/issues/1

**Comment by Quintus** [comment]
Am 09. September 2018 um 14:22 Uhr -0700 schrieb Mario Loderer:
>1280x800, 1440x900....
> Is there a way in settings? Or is this a bug?

It isn't a bug. TSC2 scales any resolution that is not of the same
aspect ratio as 1024x768 to fit that resolution's aspect ratio (which is
4:3). This is an unfortunate design decision that we have inherited from
the original SMC. As xet7 pointed out, TSC3 will do this differently by
adding black bars instead of scaling.

In any case, you can circumvent the problem by not using fullscreen mode
and playing in windowed mode instead with an appropriate window size
whose aspect ratio is 4:3. The resolution menu intends to faciliate this
by painting "good" resolutions in green and "bad" resolutions in red
when you actiate the drop-down list.

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F
