### ISSUE TITLE
Unable to look up git.guelkerdev.de

### ISSUE THREAD

**Issue by Siggemada** [Secretchronicles/TSC#644]
Cloning into '/home/xxx/TSC/tinyclipboard'...
fatal: Unable to look up git.guelkerdev.de (port 9418) (Temporary failure in name resolution)
fatal: clone of 'git://git.guelkerdev.de/tinyclipboard.git' into submodule path '/home/xxx/TSC/tinyclipboard' failed
Failed to clone 'tinyclipboard'. Retry scheduled
Cloning into '/home/xxx/TSC/tinyclipboard'...
fatal: Unable to look up git.guelkerdev.de (port 9418) (Temporary failure in name resolution)
fatal: clone of 'git://git.guelkerdev.de/tinyclipboard.git' into submodule path '/home/xxx/TSC/tinyclipboard' failed
Failed to clone 'tinyclipboard' a second time, aborting

**Comment by Siggemada** [comment]
Build instructions does not work.

**Comment by Quintus** [comment]
Oh, that's my fault. I gave the `guelkerdev.de` domain up and moved to `guelker.eu`. I fix this, wait a moment...

**Comment by Quintus** [comment]
Try again, it should work now.

**Comment by Siggemada** [comment]
Yes, success! Thanks!

**Comment by rezso** [comment]
git.guelker.eu not works:

fatal: unable to connect to git.guelker.eu:
git.guelker.eu[0: 92.116.18.163]: errno=no route

**Comment by Quintus** [comment]
There was a small outage on my server. Things should now work again.

  -quintus

Am 11. Februar 2020 um 07:11 Uhr -0800 schrieb rezso:
>git.guelker.eu not works:
>
>fatal: unable to connect to git.guelker.eu:
>git.guelker.eu[0: 92.116.18.163]: errno=no route
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/Secretchronicles/TSC/issues/644#issuecomment-584682802

-- 
Blog: https://mg.guelker.eu

**Comment by programmingkidx** [comment]
Hi, I tired cloning the repo and it timed out.

git clone git://git.guelkerdev.de/tinyclipboard.git
Cloning into 'tinyclipboard'...
fatal: unable to connect to git.guelkerdev.de:
git.guelkerdev.de[0: 91.195.241.136]: errno=Operation timed out

**Comment by xet7** [comment]
@programmingkidx 

Sorry, that server is temporarily not available, and it will take some time when it'll be online again.

Meanwhile, I added those missing submodules to .zip files at here:
https://ftp.secretchronicles.org/submodules/

You see list of submodules this way:
```
git clone https://github.com/Secretchronicles/TSC
cd TSC
cat .gitmodules
```

**Comment by rezso** [comment]
I think, you can add a github mirror for these submodules.

**Comment by Quintus** [comment]
These submodules do not exist anymore in the current master and devel
branches. They have moved to the guelker.eu domain, which is perfectly
available. What are you trying to build?

  -quintus

-- 
Dipl.-Jur. M. Gülker | https://mg.guelker.eu |    For security:
Unna, Germany        | kontakt@guelker.eu    | () Avoid HTML e-mail
European Union       | PGP: see homepage     | /\ http://asciiribbon.org

**Comment by xet7** [comment]
@Quintus 

I think those submodules at https://github.com/Secretchronicles/TSC/blob/devel/.gitmodules#L6 and https://github.com/Secretchronicles/TSC/blob/devel/.gitmodules#L15 were not available when they were trying to clone TSC for building from source. So this means there is new comments to this issue every time guelker.eu is unavailable, because those repos are not hosted at GitHub.

**Comment by Quintus** [comment]
The poster said that modules from "git.guelkerdev.de" are not available. The
modules you linked to are from "git.guelker.eu". I suspect the OP has not
run $ git submodule update since a long time. This is a different issue
from the one reported originally in this thread.

"guelker.eu" is normally available. If you deem it necessary, you can
mirror the repositories as it's open-source software, but I will
maintain them primaryly over on my own infrastructure. That being said,
tinyclipboard is currently getting superfluous as SFML recently added
APIs for accessing the system clipboard. pod-cpp has always been
optional as it is only used for building the documentation.

The actual problem, I think, is that an ordinary $ git update does not
automatically update the submodules. I kind of dislike submodules due to
this; it can introduce subtle errors if for instance only a version
update is missing.

  -quintus

-- 
Dipl.-Jur. M. Gülker | https://mg.guelker.eu |    For security:
Unna, Germany        | kontakt@guelker.eu    | () Avoid HTML e-mail
European Union       | PGP: see homepage     | /\ http://asciiribbon.org

**Comment by Quintus** [comment]
> SFML recently added APIs for accessing the system clipboard.

I have opened #690 for replacing tinyclipboard.
