### ISSUE TITLE
a secret maryo chronicles version?

### ISSUE THREAD

**Issue by pirate486743186** [Secretchronicles/TSC#654]
I see, that you guys plan on completely changing the original game, and actually have already started.

Given that the original game is  no longer maintained and the binaries are getting old. It would be nice if there was a version with the original game unchanged (minus the bugs). At least until you start breaking backward compatibility too much.

At least release one version of this as a flatpack (linux). This way the binaries will be runnable, for a very long time.

**Comment by xet7** [comment]
Original SMC does not even compile properly on current distros, it's not possible to make releases for it. Current TSC2 on this repo works and there will be flatpak version. TSC3 has only small amount of beginning test code, there is no playability yet at all.

**Comment by Quintus** [comment]
Good afternoon,

to give a little more context: there is a rewrite in the pipeline which
we handle under the name TSC3. This rewrite is going to be a very large
departure from the current state of TSC, but as xet7 correctly pointed
out, there is very little code on that front available yet. For a long
time, this is not going to change due to time constraints. Specifically,
I am in the final phase of my university studies and thus only find
little time to work on TSC.

TSC 2.1, the current version of TSC as it is developed in the `devel`
branch, is based on the original SMC code, with lots of bugfixes and
many new features. As of now, it is not an entirely new game compared to
SMC, but mostly "SMC enhanced". In the course of TSC 2 development, we
will probably make minor to medium changes to the game (over several
releases), but I expect that the original character of SMC will be
visible for years to come, even if just because of all the work. Thus,
you already have your "maintained SMC with bugfixes" if you just run TSC
2.1 from the `devel` branch. The 2.1 release is not going to be much
different from the state you currently have in `devel`.

The most notable change we are currently working on is integrating story
into the game. The idea of a story is not TSC-specific; it was long
planned even for SMC, but it was never implemented by FluXy (the
original SMC lead developer). We do have our own idea of a story, that's
right, though. It however is likely that the 2.1 release will only
contain a few story-related fragments. I expect the story part to grow
over the course of multiple releases.

  -quintus

-- 
Blog: https://mg.guelker.eu

**Comment by pirate486743186** [comment]
You haven't changed some graphics already?
I see discussions of new graphics, and removing pipes, it looks too much like mario etc...

I really meant, to use TSC2 binary with the original SMC data files as a "pirate" SMC version. I'm not talking about the internal plumbing, i'm talking about the way it looks from the point of view of the player (sound, music, sprites, AI, gameplay etc...).

The TSC2.1 binary, is still compatible with the original unmodified data files? The Data files of TSC where changed right?

Do, a bit like what scummvm does. Got it? At least one flatpack, as faithfull as possible to the original(from a user's perspective), would be nice(minus some bugs), just for preservation. Beyond that, do what you want.

**Comment by xet7** [comment]
@pirate486743186 

Original SMC was the "pirate" version. After that, code has been cleaned up, upgraded, with new graphics, sounds, music, etc. TSC2 is getting away from SMC by making TSC2 more original and different.

TSC2 is not an emulator, and it can not be used to run any other games. So it's not anything like scummvm.

TSC2 is game code with C++, with a lot of bugfixes so that TSC2 runs on current distros.

Sure you could try TSC2 with SMC data files, but I don't know does it work at all.

**Comment by xet7** [comment]
@pirate486743186 

Current levels in TSC2 have many fixes compared to original SMC, so it's possible to play through TSC2 levels. I don't see any reason to use old buggy SMC.

**Comment by pirate486743186** [comment]
scummvm is not an emulator, it's recreated game engines. Some times from scratch, some times **with the original source code**.

What i'm saying. Something that looks like SMC, that stays true to it self, but with bug fixes and compatibility with a modern system. Like playing a scummvm game, you expect it to look and play the same, but still be native to a modern PC.

I'm assuming that In practice. TSC2 binaries with just the old art should do the trick, and that would be painless and easy, unless you already made deeper changes.

**Comment by Quintus** [comment]
Hi,

I agree with xet7. There's no need to revive the old and buggy SMC. The
original SMC code is available for anybody to work with:

<https://github.com/FluXy/SMC>

As xet7 suggested, you could try to use the SMC graphics set as
contained in that repository unmodified with the TSC code. Replace the
entire data/ directory. It should mostly work, but some graphics changed
dimensions in TSC and I think some of the more obscure level features
could have been broken with nobody noticing.

We do not have the manpower to do a SMC hommage edition.

  -quintus

-- 
Blog: https://mg.guelker.eu
