### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#657]
@refi64, could you please take a look at this ever-failing Travis checks? If you don't like to fix it, please just remove the Travis support. The way it currently complains on all PRs is just annoying.

**Comment by refi64** [comment]
Will do, it might be also worth doing another CI since the new owners of Travis apparently laid off a chunk of their team and the future of the OSS version is in doubt...

**Comment by Quintus** [comment]
In ticket #427 we didn't get anywhere with unit tests for TSC, and I haven't changed my mind on the topic of testing games either (see there for explanation). For the foreseeable future, this means that TSC will not have any tests at all. The CI system would thus basically only test if the code still builds. Since anybody can do that with a simple compilation, I doubt that we need a CI system at all.

I'd thus suggest simple removal.

**Comment by refi64** [comment]
I...actually just realized I never did anything with the branch I had to fix Travis and use it for automated AppImage builds because I was waiting for server-end stuff. On the new one I could maybe DIY hosting a Flatpak repo with test builds, since [the server Flathub uses is open source anyway](https://github.com/alexlarsson/repo-manager). Just a thought?

**Comment by Quintus** [comment]
Since I'd like to keep out of the Flatpak issues personally, you can
just use whatever websites and tooling you deem necessary, whether it's
hosted on alexandria or not. If you do need or want something on
alexandria, ask @sydneyjd if he can look into it. For the purpose of
this ticket it's only important what happens to Travis.

-- 
Blog: https://mg.guelker.eu
