### ISSUE TITLE
TSC2 with CEGUI on Debian 10 ?

### ISSUE THREAD

**Issue by xet7** [Secretchronicles/TSC#658]
Hi,
is it in any way possible to get CEGUI for Debian 10 ?

Currently I can not use Ubuntu 19.04 based distros (that have kernel 5.x) on my Core 2 Duo laptop that has 8 GB RAM and 500 GB SSD. This is because when opening Firefox, desktop freezes.

I did install Debian 10 so that I could get some stability.

Problem is, CEGUI is not in Debian 10 repos. I did try to build it for some hours without success. I presume getting TSC3 working would require a lot of time.

Some options:
- Could someone give Info how to get CEGUI deb packages built for Debian 10, so that they could be hosted on Alexandria? Or would it even be possible to get them included to Debian 10 ?
- Is there any existing CEGUI packages for Debian 10 ?
- I have thinked would upgrading to Debian sid help, probably there CEGUI is available, but I don't know how stable Debian sid is.
- Recommendations welcome for some other more lightwieight OS where TSC would already have existing prebuilt dependencies like CEGUI etc.

**Comment by refi64** [comment]
There's nothing for earlier Debian versions, but sid does have cegui:
https://packages.debian.org/sid/libcegui-mk2-0.8.7

IMO the issue with newer kernels should try to be resolved regardless,
however (hit me up on irc and I can try to help debug it).

*cough* you could always use the Flatpak *cough*

**Comment by Quintus** [comment]
If you want precompiled CEGUI packages, you best ask the CEGUI
developers if they can provide them: http://cegui.org.uk/

Other than that, I think the problem is going to resolve itself over
time when we finally get a 2.1.0 release out and ask a Debian maintainer
to include TSC. This will get CEGUI into Debian again as well.

For the intermediate solution, refi's suggestions are fine.

-- 
Blog: https://mg.guelker.eu
