### ISSUE TITLE
Level Music Keeps Playing While Death Music Plays

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#672]
I noticed that if you die in a level, the level music already playing keeps playing while the death music begins playing.  I do not remember this behavior before -- it is traditional in games only to play the death music during death.

**Comment by Quintus** [comment]
Actually, this is intentional. In `cLevel_Player::DownGrade_Plyer()` the background music [is faded out slowly](https://github.com/Secretchronicles/TSC/blob/08396113a43f538cccb7691f6a340d144569d109/tsc/src/level/level_player.cpp#L259), and not stopped immediately. The fadeout time is set to about the duration of the death animation.

**Comment by refi64** [comment]
I kinda feel like it would be nicer if this either:

- Cuts out.
- Fades the game music but doesn't play the death music.

Right now with both it just seems weird...

**Comment by Quintus** [comment]
Appearently the majority opinion is that the music should be stopped. I add this to the 2.1.0 milestone so it will become part of the 2.1.0 release...
